package wc.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import wc.entity.TbCrmMessage;


public interface ITbCrmMessageDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_MESSAGE
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_MESSAGE
     *
     * @mbg.generated
     */
    //添加
    public int insert(TbCrmMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_MESSAGE
     *
     * @mbg.generated
     */
    TbCrmMessage selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_MESSAGE
     *
     * @mbg.generated
     */
    List<TbCrmMessage> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_MESSAGE
     *
     * @mbg.generated
     */
    //查看后更改时间
    public int updateByPrimaryKey(TbCrmMessage record);
    
    //查询自己写给别人的信
    public List<TbCrmMessage> selectBymyself(@Param("userId")int userId,@Param("page")int page,@Param("pagesize")int pagesize);
    public int findBmTotal(int userId);
    //查询别人写给自己的信
    public List<TbCrmMessage> selectByother(@Param("userId")int userId,@Param("page")int page,@Param("pagesize")int pagesize);
    public int findBoTotal(int userId);
    //查看
    public TbCrmMessage selectByid(Integer id);
    //删除
    public  boolean deleteById(Integer id);
    
}