package wc.dao;

import java.util.List;
import wc.entity.TbCrmLoginHistory;

public interface ITbCrmLoginHistoryDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_LOGIN_HISTORY
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_LOGIN_HISTORY
     *
     * @mbg.generated
     */
    int insert(TbCrmLoginHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_LOGIN_HISTORY
     *
     * @mbg.generated
     */
    TbCrmLoginHistory selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_LOGIN_HISTORY
     *
     * @mbg.generated
     */
    List<TbCrmLoginHistory> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_LOGIN_HISTORY
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TbCrmLoginHistory record);
}