package wc.dao;

import java.util.List;
import wc.entity.TbCrmBusinessStatus;

public interface ITbCrmBusinessStatusDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_BUSINESS_STATUS
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_BUSINESS_STATUS
     *
     * @mbg.generated
     */
    int insert(TbCrmBusinessStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_BUSINESS_STATUS
     *
     * @mbg.generated
     */
    TbCrmBusinessStatus selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_BUSINESS_STATUS
     *
     * @mbg.generated
     */
    List<TbCrmBusinessStatus> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_BUSINESS_STATUS
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TbCrmBusinessStatus record);
}