package wc.dao;

import java.util.List;
import wc.entity.TbCrmTask;

public interface ITbCrmTaskDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_TASK
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_TASK
     *
     * @mbg.generated
     */
    int insert(TbCrmTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_TASK
     *
     * @mbg.generated
     */
    TbCrmTask selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_TASK
     *
     * @mbg.generated
     */
    List<TbCrmTask> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_TASK
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TbCrmTask record);
}