package wc.dao;

import java.util.List;
import wc.entity.TbCrmContacts;

public interface ITbCrmContactsDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_CONTACTS
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_CONTACTS
     *
     * @mbg.generated
     */
    int insert(TbCrmContacts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_CONTACTS
     *
     * @mbg.generated
     */
    TbCrmContacts selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_CONTACTS
     *
     * @mbg.generated
     */
    List<TbCrmContacts> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_CONTACTS
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TbCrmContacts record);
}