package wc.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import wc.entity.PositionVO;
import wc.entity.TbCrmPosition;

public interface ITbCrmPositionDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_POSITION
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_POSITION
     *
     * @mbg.generated
     */
    int insert(TbCrmPosition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_POSITION
     *
     * @mbg.generated
     */
    TbCrmPosition selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_POSITION
     *
     * @mbg.generated
     */
    List<TbCrmPosition> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_POSITION
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TbCrmPosition record);

	List<PositionVO> findByPage(@Param("startNo")int startNo, @Param("endNo")int endNo);

	int findtotal();

	int findByNameTotal(String name);

	List<PositionVO> findByNamePage(@Param("startNo")int startNo, @Param("endNo")int endNo, @Param("name")String name);
}