package wc.dao;

import java.util.List;
import wc.entity.TbCrmRBusinessProduct;

public interface ITbCrmRBusinessProductDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_R_BUSINESS_PRODUCT
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_R_BUSINESS_PRODUCT
     *
     * @mbg.generated
     */
    int insert(TbCrmRBusinessProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_R_BUSINESS_PRODUCT
     *
     * @mbg.generated
     */
    TbCrmRBusinessProduct selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_R_BUSINESS_PRODUCT
     *
     * @mbg.generated
     */
    List<TbCrmRBusinessProduct> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_R_BUSINESS_PRODUCT
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TbCrmRBusinessProduct record);
}