package wc.dao;

import java.util.List;
import wc.entity.TbCrmCustomer;

public interface ITbCrmCustomerDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_CUSTOMER
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_CUSTOMER
     *
     * @mbg.generated
     */
    int insert(TbCrmCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_CUSTOMER
     *
     * @mbg.generated
     */
    TbCrmCustomer selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_CUSTOMER
     *
     * @mbg.generated
     */
    List<TbCrmCustomer> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_CUSTOMER
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TbCrmCustomer record);
}