package wc.dao;

import java.util.List;
import wc.entity.TbCrmSmsRecord;

public interface ITbCrmSmsRecordDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_SMS_RECORD
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_SMS_RECORD
     *
     * @mbg.generated
     */
    int insert(TbCrmSmsRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_SMS_RECORD
     *
     * @mbg.generated
     */
    TbCrmSmsRecord selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_SMS_RECORD
     *
     * @mbg.generated
     */
    List<TbCrmSmsRecord> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_SMS_RECORD
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TbCrmSmsRecord record);
}