package wc.dao;

import java.util.List;
import wc.entity.TbCrmProductImages;

public interface ITbCrmProductImagesDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_PRODUCT_IMAGES
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_PRODUCT_IMAGES
     *
     * @mbg.generated
     */
    int insert(TbCrmProductImages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_PRODUCT_IMAGES
     *
     * @mbg.generated
     */
    TbCrmProductImages selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_PRODUCT_IMAGES
     *
     * @mbg.generated
     */
    List<TbCrmProductImages> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_PRODUCT_IMAGES
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TbCrmProductImages record);
}