package wc.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import wc.entity.BusinessVO;
import wc.entity.ContractVO2;
import wc.entity.TbCrmBusiness;

public interface ITbCrmBusinessDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_BUSINESS
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_BUSINESS
     *
     * @mbg.generated
     */
    int insert(TbCrmBusiness record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_BUSINESS
     *
     * @mbg.generated
     */
    TbCrmBusiness selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_BUSINESS
     *
     * @mbg.generated
     */
    List<TbCrmBusiness> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_BUSINESS
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TbCrmBusiness record);
    
    List<ContractVO2> findByContractVO2();

	ContractVO2 findByIdContractVO2(int tcbsId);
	
	List<BusinessVO> findAllBusinessBy(@Param("userId")int userId, @Param("start")int start, @Param("end")int end, @Param("field")String field, @Param("value")String value);
	
	int getAllBusinessCount(@Param("userId")int userId, @Param("field")String field, @Param("value")String value);

	List<Map<String, Object>> getAllUsername();

	List<Map<String, Object>> getAllCustomerName();

	List<Map<String, Object>> getAllContactsName();
	
	String findBNameByCId(int customerId);

	int getContactsId(String contactsName);

	int updateDelete(List<Integer> list);

	int updateDeleteOne(int id);

	BusinessVO getOneBusinessVO(long l);

	int getCustomerId(String customerName);

	List<BusinessVO> findBusinessRB(@Param("value")String value,@Param("field")String field,@Param("start")int start,@Param("end")int end, @Param("startTime")String startTime, @Param("endTime")String endTime);

	int findBusinessRBCount(@Param("value")String value,@Param("field")String field,@Param("start")int start,@Param("end")int end, @Param("startTime")String startTime, @Param("endTime")String endTime);

	List<Map<String, Object>> findBusinessLogById(int id);

	Map<String, Object> findContractById(int id);

	int updateStatusBy(TbCrmBusiness b);

	int getStatusIdBy(int id);

	
	
	
}