package wc.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import wc.entity.ContractVO;
import wc.entity.PositionVO;
import wc.entity.TbCrmContract;

public interface ITbCrmContractDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_CONTRACT
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_CONTRACT
     *
     * @mbg.generated
     */
    int insert(TbCrmContract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_CONTRACT
     *
     * @mbg.generated
     */
    TbCrmContract selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_CONTRACT
     *
     * @mbg.generated
     */
    List<TbCrmContract> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_CONTRACT
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TbCrmContract record);

	List<ContractVO> findByPage(@Param("startNo")int startNo,@Param("endNo") int endNo);

	int findtotal();

	int findByNumberTotal(String number);

	List<ContractVO> findByNumberPage(@Param("startNo")int startNo,@Param("endNo") int endNo, @Param("number")String number);
}