package wc.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import wc.entity.TbCrmAnnouncement;

public interface ITbCrmAnnouncementDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_ANNOUNCEMENT
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_ANNOUNCEMENT
     *
     * @mbg.generated
     */
    int insert(TbCrmAnnouncement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_ANNOUNCEMENT
     *
     * @mbg.generated
     */
    TbCrmAnnouncement selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_ANNOUNCEMENT
     *
     * @mbg.generated
     */
    List<TbCrmAnnouncement> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_ANNOUNCEMENT
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TbCrmAnnouncement record);

	

	List<TbCrmAnnouncement> findByPage(@Param("startNo")int startNo, @Param("endNo")int endNo);

	int findTotal();

	int findByTitleTotal(String title);

	List<TbCrmAnnouncement> findByTitlePage(@Param("startNo")int startNo, @Param("endNo")int endNo ,@Param("title")String title);
}