package wc.dao;

import java.util.List;
import wc.entity.TbCrmEmailRecord;

public interface ITbCrmEmailRecordDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_EMAIL_RECORD
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_EMAIL_RECORD
     *
     * @mbg.generated
     */
    int insert(TbCrmEmailRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_EMAIL_RECORD
     *
     * @mbg.generated
     */
    TbCrmEmailRecord selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_EMAIL_RECORD
     *
     * @mbg.generated
     */
    List<TbCrmEmailRecord> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_EMAIL_RECORD
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TbCrmEmailRecord record);
}