package wc.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import wc.entity.AddLeadVO;
import wc.entity.LeadsFieldVO;
import wc.entity.LeadsVO;
import wc.entity.TbCrmLeadLog;
import wc.entity.TbCrmLeads;

public interface ITbCrmLeadsDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_LEADS
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_LEADS
     *
     * @mbg.generated
     */
    int insert(TbCrmLeads record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_LEADS
     *
     * @mbg.generated
     */
    TbCrmLeads selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_LEADS
     *
     * @mbg.generated
     */
    List<TbCrmLeads> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_LEADS
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TbCrmLeads record);
    
    public int getCount(@Param("userId")int userId, @Param("value")String value,@Param("field")String field,@Param("start")int page,@Param("end")int rows);

	List<LeadsVO> findLeadsAndUser(@Param("userId")int userId, @Param("value")String value,@Param("field")String field,@Param("start")int page,@Param("end")int rows);

	List<LeadsFieldVO> getFields();

	int updateDelete(List<Integer> list);

	List<AddLeadVO> findLeadPool(@Param("value")String value,@Param("field")String field,@Param("start")int start,@Param("end")int end, @Param("startTime")String startTime, @Param("endTime")String endTime);

	int getLeadPoolCount(@Param("value")String value,@Param("field")String field,@Param("start")int start,@Param("end")int end, @Param("startTime")String startTime, @Param("endTime")String endTime);

	LeadsVO getOneLeadVO(Long l);

	List<TbCrmLeadLog> getCCById(@Param("id")int id, @Param("start")int page,@Param("end")int rows);

	int getLeadLogCountById(int id);

	List<TbCrmLeadLog> getCCByIdAAAA(int id);

	int updateDeleteOne(int id);

	int putPool(List<Integer> list);

	List<AddLeadVO> findLeadRB(@Param("value")String value,@Param("field")String field,@Param("start")int start,@Param("end")int end, @Param("startTime")String startTime, @Param("endTime")String endTime);

	int findLeadRBCount(@Param("value")String value,@Param("field")String field,@Param("start")int start,@Param("end")int end, @Param("startTime")String startTime, @Param("endTime")String endTime);

	int reLeads(List<Integer> list);
    
}