package wc.dao;

import java.util.List;
import wc.entity.TbCrmRBusinessTask;

public interface ITbCrmRBusinessTaskDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_R_BUSINESS_TASK
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_R_BUSINESS_TASK
     *
     * @mbg.generated
     */
    int insert(TbCrmRBusinessTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_R_BUSINESS_TASK
     *
     * @mbg.generated
     */
    TbCrmRBusinessTask selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_R_BUSINESS_TASK
     *
     * @mbg.generated
     */
    List<TbCrmRBusinessTask> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_R_BUSINESS_TASK
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TbCrmRBusinessTask record);
}