package wc.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import wc.entity.TbSystemRole;

public interface ITbSystemRoleDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SYSTEM_ROLE
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SYSTEM_ROLE
     *
     * @mbg.generated
     */
    //添加
    public int insert(TbSystemRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SYSTEM_ROLE
     *
     * @mbg.generated
     */
    TbSystemRole selectByPrimaryKey(Long roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SYSTEM_ROLE
     *
     * @mbg.generated
     */
    List<TbSystemRole> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SYSTEM_ROLE
     *
     * @mbg.generated
     */
    //修改前查询
    public TbSystemRole listByid(Integer roleId);
    //修改
    public int updateByPrimaryKey(TbSystemRole role);
    
    //分页查询
    public List<TbSystemRole> findByPage(@Param("page")int page,@Param("pagesize")int pagesize);
    public int findTotal();
    
    
        
    //删除
    public  boolean deleteById(Integer roleId);
    
    public List<TbSystemRole> findRolesByIds(List<Integer> list);
}