package wc.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import wc.entity.TbSystemUser;


public interface ITbSystemUserDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SYSTEM_USER
     *
     * @mbg.generated
     */
	
    int deleteByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SYSTEM_USER
     *
     * @mbg.generated
     */
    //添加
    public int insert(TbSystemUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SYSTEM_USER
     *
     * @mbg.generated
     */
    TbSystemUser selectByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SYSTEM_USER
     *
     * @mbg.generated
     */
    public List<TbSystemUser> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SYSTEM_USER
     *
     * @mbg.generated
     */
    //修改
    public int updateByPrimaryKey(TbSystemUser user);
    
    
    public TbSystemUser login(@Param("username")String username, @Param("password")String password);
    
    public int findUserId(String username);
    /**
     * @author jbj
     * 根据Id查询系统用户名
     */
	String findUsernameById(Long userId);
	/**
     * @author jbj
     * 根据系统用户名查询Id
     */
	Long findByName(@Param("username")String username);
    
    //分页查询
    public List<TbSystemUser> findByPage(@Param("page")int page,@Param("pagesize")int pagesize);
    public int findTotal();
    
    //修改前查询
    public TbSystemUser listByid(Integer userId);
    
    //删除
    public  boolean deleteById(Integer userId);
    
    
    
}