package wc.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import wc.entity.TbSystemUserRole;



public interface ITbSystemUserRoleDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SYSTEM_USER_ROLE
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("userId") Long userId, @Param("roleId") Long roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SYSTEM_USER_ROLE
     *
     * @mbg.generated
     */
    

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SYSTEM_USER_ROLE
     *
     * @mbg.generated
     */
    List<TbSystemUserRole> selectAll();
    
    
    public List<TbSystemUserRole> findRoleByUserId(int id);
    
    //ÊÚÈ¨
    public int insert(TbSystemUserRole record);
    public List<TbSystemUserRole> findByUserId(Integer userId);
    public int deleteByUserId(Integer userId);
    
    
}