package wc.entity;

import java.util.Date;

public class TbCrmProductImages {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_PRODUCT_IMAGES.ID
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_PRODUCT_IMAGES.PRODUCT_ID
     *
     * @mbg.generated
     */
    private Long productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_PRODUCT_IMAGES.IS_MAIN
     *
     * @mbg.generated
     */
    private Short isMain;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_PRODUCT_IMAGES.NAME
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_PRODUCT_IMAGES.SAVE_NAME
     *
     * @mbg.generated
     */
    private String saveName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_PRODUCT_IMAGES.size
     *
     * @mbg.generated
     */
    private String size;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_PRODUCT_IMAGES.PATH
     *
     * @mbg.generated
     */
    private String path;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_PRODUCT_IMAGES.CREATE_TIME
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_PRODUCT_IMAGES.SORTNUM
     *
     * @mbg.generated
     */
    private Long sortnum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_PRODUCT_IMAGES.ID
     *
     * @return the value of TB_CRM_PRODUCT_IMAGES.ID
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_PRODUCT_IMAGES.ID
     *
     * @param id the value for TB_CRM_PRODUCT_IMAGES.ID
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_PRODUCT_IMAGES.PRODUCT_ID
     *
     * @return the value of TB_CRM_PRODUCT_IMAGES.PRODUCT_ID
     *
     * @mbg.generated
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_PRODUCT_IMAGES.PRODUCT_ID
     *
     * @param productId the value for TB_CRM_PRODUCT_IMAGES.PRODUCT_ID
     *
     * @mbg.generated
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_PRODUCT_IMAGES.IS_MAIN
     *
     * @return the value of TB_CRM_PRODUCT_IMAGES.IS_MAIN
     *
     * @mbg.generated
     */
    public Short getIsMain() {
        return isMain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_PRODUCT_IMAGES.IS_MAIN
     *
     * @param isMain the value for TB_CRM_PRODUCT_IMAGES.IS_MAIN
     *
     * @mbg.generated
     */
    public void setIsMain(Short isMain) {
        this.isMain = isMain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_PRODUCT_IMAGES.NAME
     *
     * @return the value of TB_CRM_PRODUCT_IMAGES.NAME
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_PRODUCT_IMAGES.NAME
     *
     * @param name the value for TB_CRM_PRODUCT_IMAGES.NAME
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_PRODUCT_IMAGES.SAVE_NAME
     *
     * @return the value of TB_CRM_PRODUCT_IMAGES.SAVE_NAME
     *
     * @mbg.generated
     */
    public String getSaveName() {
        return saveName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_PRODUCT_IMAGES.SAVE_NAME
     *
     * @param saveName the value for TB_CRM_PRODUCT_IMAGES.SAVE_NAME
     *
     * @mbg.generated
     */
    public void setSaveName(String saveName) {
        this.saveName = saveName == null ? null : saveName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_PRODUCT_IMAGES.size
     *
     * @return the value of TB_CRM_PRODUCT_IMAGES.size
     *
     * @mbg.generated
     */
    public String getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_PRODUCT_IMAGES.size
     *
     * @param size the value for TB_CRM_PRODUCT_IMAGES.size
     *
     * @mbg.generated
     */
    public void setSize(String size) {
        this.size = size == null ? null : size.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_PRODUCT_IMAGES.PATH
     *
     * @return the value of TB_CRM_PRODUCT_IMAGES.PATH
     *
     * @mbg.generated
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_PRODUCT_IMAGES.PATH
     *
     * @param path the value for TB_CRM_PRODUCT_IMAGES.PATH
     *
     * @mbg.generated
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_PRODUCT_IMAGES.CREATE_TIME
     *
     * @return the value of TB_CRM_PRODUCT_IMAGES.CREATE_TIME
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_PRODUCT_IMAGES.CREATE_TIME
     *
     * @param createTime the value for TB_CRM_PRODUCT_IMAGES.CREATE_TIME
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_PRODUCT_IMAGES.SORTNUM
     *
     * @return the value of TB_CRM_PRODUCT_IMAGES.SORTNUM
     *
     * @mbg.generated
     */
    public Long getSortnum() {
        return sortnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_PRODUCT_IMAGES.SORTNUM
     *
     * @param sortnum the value for TB_CRM_PRODUCT_IMAGES.SORTNUM
     *
     * @mbg.generated
     */
    public void setSortnum(Long sortnum) {
        this.sortnum = sortnum;
    }
}