package wc.entity;

import java.util.Date;

public class TbCrmTask {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_TASK.ID
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_TASK.OWNER_USER_ID
     *
     * @mbg.generated
     */
    private Long ownerUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_TASK.ABOUT_USERS
     *
     * @mbg.generated
     */
    private String aboutUsers;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_TASK.SUBJECT
     *
     * @mbg.generated
     */
    private String subject;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_TASK.DUE_DATE
     *
     * @mbg.generated
     */
    private Date dueDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_TASK.STATUS
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_TASK.PRIORITY
     *
     * @mbg.generated
     */
    private String priority;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_TASK.CREATOR_USER_ID
     *
     * @mbg.generated
     */
    private Long creatorUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_TASK.CREATE_DATE
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_TASK.UPDATE_DATE
     *
     * @mbg.generated
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_TASK.ISCLOSE
     *
     * @mbg.generated
     */
    private Short isclose;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_TASK.DELETE_STATUS
     *
     * @mbg.generated
     */
    private Short deleteStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_TASK.DELETE_USER_ID
     *
     * @mbg.generated
     */
    private Long deleteUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_TASK.DELETE_TIME
     *
     * @mbg.generated
     */
    private Date deleteTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_TASK.DESCRIPTION
     *
     * @mbg.generated
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_TASK.ID
     *
     * @return the value of TB_CRM_TASK.ID
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_TASK.ID
     *
     * @param id the value for TB_CRM_TASK.ID
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_TASK.OWNER_USER_ID
     *
     * @return the value of TB_CRM_TASK.OWNER_USER_ID
     *
     * @mbg.generated
     */
    public Long getOwnerUserId() {
        return ownerUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_TASK.OWNER_USER_ID
     *
     * @param ownerUserId the value for TB_CRM_TASK.OWNER_USER_ID
     *
     * @mbg.generated
     */
    public void setOwnerUserId(Long ownerUserId) {
        this.ownerUserId = ownerUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_TASK.ABOUT_USERS
     *
     * @return the value of TB_CRM_TASK.ABOUT_USERS
     *
     * @mbg.generated
     */
    public String getAboutUsers() {
        return aboutUsers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_TASK.ABOUT_USERS
     *
     * @param aboutUsers the value for TB_CRM_TASK.ABOUT_USERS
     *
     * @mbg.generated
     */
    public void setAboutUsers(String aboutUsers) {
        this.aboutUsers = aboutUsers == null ? null : aboutUsers.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_TASK.SUBJECT
     *
     * @return the value of TB_CRM_TASK.SUBJECT
     *
     * @mbg.generated
     */
    public String getSubject() {
        return subject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_TASK.SUBJECT
     *
     * @param subject the value for TB_CRM_TASK.SUBJECT
     *
     * @mbg.generated
     */
    public void setSubject(String subject) {
        this.subject = subject == null ? null : subject.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_TASK.DUE_DATE
     *
     * @return the value of TB_CRM_TASK.DUE_DATE
     *
     * @mbg.generated
     */
    public Date getDueDate() {
        return dueDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_TASK.DUE_DATE
     *
     * @param dueDate the value for TB_CRM_TASK.DUE_DATE
     *
     * @mbg.generated
     */
    public void setDueDate(Date dueDate) {
        this.dueDate = dueDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_TASK.STATUS
     *
     * @return the value of TB_CRM_TASK.STATUS
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_TASK.STATUS
     *
     * @param status the value for TB_CRM_TASK.STATUS
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_TASK.PRIORITY
     *
     * @return the value of TB_CRM_TASK.PRIORITY
     *
     * @mbg.generated
     */
    public String getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_TASK.PRIORITY
     *
     * @param priority the value for TB_CRM_TASK.PRIORITY
     *
     * @mbg.generated
     */
    public void setPriority(String priority) {
        this.priority = priority == null ? null : priority.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_TASK.CREATOR_USER_ID
     *
     * @return the value of TB_CRM_TASK.CREATOR_USER_ID
     *
     * @mbg.generated
     */
    public Long getCreatorUserId() {
        return creatorUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_TASK.CREATOR_USER_ID
     *
     * @param creatorUserId the value for TB_CRM_TASK.CREATOR_USER_ID
     *
     * @mbg.generated
     */
    public void setCreatorUserId(Long creatorUserId) {
        this.creatorUserId = creatorUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_TASK.CREATE_DATE
     *
     * @return the value of TB_CRM_TASK.CREATE_DATE
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_TASK.CREATE_DATE
     *
     * @param createDate the value for TB_CRM_TASK.CREATE_DATE
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_TASK.UPDATE_DATE
     *
     * @return the value of TB_CRM_TASK.UPDATE_DATE
     *
     * @mbg.generated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_TASK.UPDATE_DATE
     *
     * @param updateDate the value for TB_CRM_TASK.UPDATE_DATE
     *
     * @mbg.generated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_TASK.ISCLOSE
     *
     * @return the value of TB_CRM_TASK.ISCLOSE
     *
     * @mbg.generated
     */
    public Short getIsclose() {
        return isclose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_TASK.ISCLOSE
     *
     * @param isclose the value for TB_CRM_TASK.ISCLOSE
     *
     * @mbg.generated
     */
    public void setIsclose(Short isclose) {
        this.isclose = isclose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_TASK.DELETE_STATUS
     *
     * @return the value of TB_CRM_TASK.DELETE_STATUS
     *
     * @mbg.generated
     */
    public Short getDeleteStatus() {
        return deleteStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_TASK.DELETE_STATUS
     *
     * @param deleteStatus the value for TB_CRM_TASK.DELETE_STATUS
     *
     * @mbg.generated
     */
    public void setDeleteStatus(Short deleteStatus) {
        this.deleteStatus = deleteStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_TASK.DELETE_USER_ID
     *
     * @return the value of TB_CRM_TASK.DELETE_USER_ID
     *
     * @mbg.generated
     */
    public Long getDeleteUserId() {
        return deleteUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_TASK.DELETE_USER_ID
     *
     * @param deleteUserId the value for TB_CRM_TASK.DELETE_USER_ID
     *
     * @mbg.generated
     */
    public void setDeleteUserId(Long deleteUserId) {
        this.deleteUserId = deleteUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_TASK.DELETE_TIME
     *
     * @return the value of TB_CRM_TASK.DELETE_TIME
     *
     * @mbg.generated
     */
    public Date getDeleteTime() {
        return deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_TASK.DELETE_TIME
     *
     * @param deleteTime the value for TB_CRM_TASK.DELETE_TIME
     *
     * @mbg.generated
     */
    public void setDeleteTime(Date deleteTime) {
        this.deleteTime = deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_TASK.DESCRIPTION
     *
     * @return the value of TB_CRM_TASK.DESCRIPTION
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_TASK.DESCRIPTION
     *
     * @param description the value for TB_CRM_TASK.DESCRIPTION
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}