package wc.entity;

public class TbCrmRBusinessTask {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_R_BUSINESS_TASK.ID
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_R_BUSINESS_TASK.BUSINESS_ID
     *
     * @mbg.generated
     */
    private Long businessId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_R_BUSINESS_TASK.TASK_ID
     *
     * @mbg.generated
     */
    private Long taskId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_R_BUSINESS_TASK.ID
     *
     * @return the value of TB_CRM_R_BUSINESS_TASK.ID
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_R_BUSINESS_TASK.ID
     *
     * @param id the value for TB_CRM_R_BUSINESS_TASK.ID
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_R_BUSINESS_TASK.BUSINESS_ID
     *
     * @return the value of TB_CRM_R_BUSINESS_TASK.BUSINESS_ID
     *
     * @mbg.generated
     */
    public Long getBusinessId() {
        return businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_R_BUSINESS_TASK.BUSINESS_ID
     *
     * @param businessId the value for TB_CRM_R_BUSINESS_TASK.BUSINESS_ID
     *
     * @mbg.generated
     */
    public void setBusinessId(Long businessId) {
        this.businessId = businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_R_BUSINESS_TASK.TASK_ID
     *
     * @return the value of TB_CRM_R_BUSINESS_TASK.TASK_ID
     *
     * @mbg.generated
     */
    public Long getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_R_BUSINESS_TASK.TASK_ID
     *
     * @param taskId the value for TB_CRM_R_BUSINESS_TASK.TASK_ID
     *
     * @mbg.generated
     */
    public void setTaskId(Long taskId) {
        this.taskId = taskId;
    }
}