package wc.entity;

import java.util.Date;

public class TbCrmMessage {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_MESSAGE.ID
     *
     * @mbg.generated
     */
    private int id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_MESSAGE.TO_USER_ID
     *
     * @mbg.generated
     */
    private int toUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_MESSAGE.FROM_USER_ID
     *
     * @mbg.generated
     */
    private int fromUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_MESSAGE.READ_TIME
     *
     * @mbg.generated
     */
    private String readTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_MESSAGE.SEND_TIME
     *
     * @mbg.generated
     */
    private String sendTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_MESSAGE.STATUS
     *
     * @mbg.generated
     */
    private Short status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_MESSAGE.CONTENT
     *
     * @mbg.generated
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_MESSAGE.ID
     *
     * @return the value of TB_CRM_MESSAGE.ID
     *
     * @mbg.generated
     */
    public int getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_MESSAGE.ID
     *
     * @param id the value for TB_CRM_MESSAGE.ID
     *
     * @mbg.generated
     */
    public void setId(int id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_MESSAGE.TO_USER_ID
     *
     * @return the value of TB_CRM_MESSAGE.TO_USER_ID
     *
     * @mbg.generated
     */
    public int getToUserId() {
        return toUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_MESSAGE.TO_USER_ID
     *
     * @param toUserId the value for TB_CRM_MESSAGE.TO_USER_ID
     *
     * @mbg.generated
     */
    public void setToUserId(int toUserId) {
        this.toUserId = toUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_MESSAGE.FROM_USER_ID
     *
     * @return the value of TB_CRM_MESSAGE.FROM_USER_ID
     *
     * @mbg.generated
     */
    public int getFromUserId() {
        return fromUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_MESSAGE.FROM_USER_ID
     *
     * @param fromUserId the value for TB_CRM_MESSAGE.FROM_USER_ID
     *
     * @mbg.generated
     */
    public void setFromUserId(int fromUserId) {
        this.fromUserId = fromUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_MESSAGE.READ_TIME
     *
     * @return the value of TB_CRM_MESSAGE.READ_TIME
     *
     * @mbg.generated
     */
    public String getReadTime() {
        return readTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_MESSAGE.READ_TIME
     *
     * @param readTime the value for TB_CRM_MESSAGE.READ_TIME
     *
     * @mbg.generated
     */
    public void setReadTime(String readTime) {
        this.readTime = readTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_MESSAGE.SEND_TIME
     *
     * @return the value of TB_CRM_MESSAGE.SEND_TIME
     *
     * @mbg.generated
     */
    public String getSendTime() {
        return sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_MESSAGE.SEND_TIME
     *
     * @param sendTime the value for TB_CRM_MESSAGE.SEND_TIME
     *
     * @mbg.generated
     */
    public void setSendTime(String sendTime) {
        this.sendTime = sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_MESSAGE.STATUS
     *
     * @return the value of TB_CRM_MESSAGE.STATUS
     *
     * @mbg.generated
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_MESSAGE.STATUS
     *
     * @param status the value for TB_CRM_MESSAGE.STATUS
     *
     * @mbg.generated
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_MESSAGE.CONTENT
     *
     * @return the value of TB_CRM_MESSAGE.CONTENT
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_MESSAGE.CONTENT
     *
     * @param content the value for TB_CRM_MESSAGE.CONTENT
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}