package wc.entity;

import java.util.Date;

public class TbCrmContacts {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_CONTACTS.ID
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_CONTACTS.CREATOR_USER_ID
     *
     * @mbg.generated
     */
    private Long creatorUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_CONTACTS.NAME
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_CONTACTS.POST
     *
     * @mbg.generated
     */
    private String post;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_CONTACTS.DEPARTMENT
     *
     * @mbg.generated
     */
    private String department;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_CONTACTS.SEX
     *
     * @mbg.generated
     */
    private Short sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_CONTACTS.SALTNAME
     *
     * @mbg.generated
     */
    private String saltname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_CONTACTS.TELEPHONE
     *
     * @mbg.generated
     */
    private String telephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_CONTACTS.EMAIL
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_CONTACTS.QQ_NO
     *
     * @mbg.generated
     */
    private String qqNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_CONTACTS.ADDRESS
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_CONTACTS.ZIP_CODE
     *
     * @mbg.generated
     */
    private String zipCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_CONTACTS.DESCRIPTION
     *
     * @mbg.generated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_CONTACTS.CUSTOMER_ID
     *
     * @mbg.generated
     */
    private Long customerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_CONTACTS.CREATE_TIME
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_CONTACTS.UPDATE_TIME
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_CONTACTS.DELETE_STATUS
     *
     * @mbg.generated
     */
    private Short deleteStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_CONTACTS.DELETE_USER_ID
     *
     * @mbg.generated
     */
    private Long deleteUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_CONTACTS.DELETE_TIME
     *
     * @mbg.generated
     */
    private Date deleteTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_CONTACTS.ID
     *
     * @return the value of TB_CRM_CONTACTS.ID
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_CONTACTS.ID
     *
     * @param id the value for TB_CRM_CONTACTS.ID
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_CONTACTS.CREATOR_USER_ID
     *
     * @return the value of TB_CRM_CONTACTS.CREATOR_USER_ID
     *
     * @mbg.generated
     */
    public Long getCreatorUserId() {
        return creatorUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_CONTACTS.CREATOR_USER_ID
     *
     * @param creatorUserId the value for TB_CRM_CONTACTS.CREATOR_USER_ID
     *
     * @mbg.generated
     */
    public void setCreatorUserId(Long creatorUserId) {
        this.creatorUserId = creatorUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_CONTACTS.NAME
     *
     * @return the value of TB_CRM_CONTACTS.NAME
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_CONTACTS.NAME
     *
     * @param name the value for TB_CRM_CONTACTS.NAME
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_CONTACTS.POST
     *
     * @return the value of TB_CRM_CONTACTS.POST
     *
     * @mbg.generated
     */
    public String getPost() {
        return post;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_CONTACTS.POST
     *
     * @param post the value for TB_CRM_CONTACTS.POST
     *
     * @mbg.generated
     */
    public void setPost(String post) {
        this.post = post == null ? null : post.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_CONTACTS.DEPARTMENT
     *
     * @return the value of TB_CRM_CONTACTS.DEPARTMENT
     *
     * @mbg.generated
     */
    public String getDepartment() {
        return department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_CONTACTS.DEPARTMENT
     *
     * @param department the value for TB_CRM_CONTACTS.DEPARTMENT
     *
     * @mbg.generated
     */
    public void setDepartment(String department) {
        this.department = department == null ? null : department.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_CONTACTS.SEX
     *
     * @return the value of TB_CRM_CONTACTS.SEX
     *
     * @mbg.generated
     */
    public Short getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_CONTACTS.SEX
     *
     * @param sex the value for TB_CRM_CONTACTS.SEX
     *
     * @mbg.generated
     */
    public void setSex(Short sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_CONTACTS.SALTNAME
     *
     * @return the value of TB_CRM_CONTACTS.SALTNAME
     *
     * @mbg.generated
     */
    public String getSaltname() {
        return saltname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_CONTACTS.SALTNAME
     *
     * @param saltname the value for TB_CRM_CONTACTS.SALTNAME
     *
     * @mbg.generated
     */
    public void setSaltname(String saltname) {
        this.saltname = saltname == null ? null : saltname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_CONTACTS.TELEPHONE
     *
     * @return the value of TB_CRM_CONTACTS.TELEPHONE
     *
     * @mbg.generated
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_CONTACTS.TELEPHONE
     *
     * @param telephone the value for TB_CRM_CONTACTS.TELEPHONE
     *
     * @mbg.generated
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_CONTACTS.EMAIL
     *
     * @return the value of TB_CRM_CONTACTS.EMAIL
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_CONTACTS.EMAIL
     *
     * @param email the value for TB_CRM_CONTACTS.EMAIL
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_CONTACTS.QQ_NO
     *
     * @return the value of TB_CRM_CONTACTS.QQ_NO
     *
     * @mbg.generated
     */
    public String getQqNo() {
        return qqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_CONTACTS.QQ_NO
     *
     * @param qqNo the value for TB_CRM_CONTACTS.QQ_NO
     *
     * @mbg.generated
     */
    public void setQqNo(String qqNo) {
        this.qqNo = qqNo == null ? null : qqNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_CONTACTS.ADDRESS
     *
     * @return the value of TB_CRM_CONTACTS.ADDRESS
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_CONTACTS.ADDRESS
     *
     * @param address the value for TB_CRM_CONTACTS.ADDRESS
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_CONTACTS.ZIP_CODE
     *
     * @return the value of TB_CRM_CONTACTS.ZIP_CODE
     *
     * @mbg.generated
     */
    public String getZipCode() {
        return zipCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_CONTACTS.ZIP_CODE
     *
     * @param zipCode the value for TB_CRM_CONTACTS.ZIP_CODE
     *
     * @mbg.generated
     */
    public void setZipCode(String zipCode) {
        this.zipCode = zipCode == null ? null : zipCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_CONTACTS.DESCRIPTION
     *
     * @return the value of TB_CRM_CONTACTS.DESCRIPTION
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_CONTACTS.DESCRIPTION
     *
     * @param description the value for TB_CRM_CONTACTS.DESCRIPTION
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_CONTACTS.CUSTOMER_ID
     *
     * @return the value of TB_CRM_CONTACTS.CUSTOMER_ID
     *
     * @mbg.generated
     */
    public Long getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_CONTACTS.CUSTOMER_ID
     *
     * @param customerId the value for TB_CRM_CONTACTS.CUSTOMER_ID
     *
     * @mbg.generated
     */
    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_CONTACTS.CREATE_TIME
     *
     * @return the value of TB_CRM_CONTACTS.CREATE_TIME
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_CONTACTS.CREATE_TIME
     *
     * @param createTime the value for TB_CRM_CONTACTS.CREATE_TIME
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_CONTACTS.UPDATE_TIME
     *
     * @return the value of TB_CRM_CONTACTS.UPDATE_TIME
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_CONTACTS.UPDATE_TIME
     *
     * @param updateTime the value for TB_CRM_CONTACTS.UPDATE_TIME
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_CONTACTS.DELETE_STATUS
     *
     * @return the value of TB_CRM_CONTACTS.DELETE_STATUS
     *
     * @mbg.generated
     */
    public Short getDeleteStatus() {
        return deleteStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_CONTACTS.DELETE_STATUS
     *
     * @param deleteStatus the value for TB_CRM_CONTACTS.DELETE_STATUS
     *
     * @mbg.generated
     */
    public void setDeleteStatus(Short deleteStatus) {
        this.deleteStatus = deleteStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_CONTACTS.DELETE_USER_ID
     *
     * @return the value of TB_CRM_CONTACTS.DELETE_USER_ID
     *
     * @mbg.generated
     */
    public Long getDeleteUserId() {
        return deleteUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_CONTACTS.DELETE_USER_ID
     *
     * @param deleteUserId the value for TB_CRM_CONTACTS.DELETE_USER_ID
     *
     * @mbg.generated
     */
    public void setDeleteUserId(Long deleteUserId) {
        this.deleteUserId = deleteUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_CONTACTS.DELETE_TIME
     *
     * @return the value of TB_CRM_CONTACTS.DELETE_TIME
     *
     * @mbg.generated
     */
    public Date getDeleteTime() {
        return deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_CONTACTS.DELETE_TIME
     *
     * @param deleteTime the value for TB_CRM_CONTACTS.DELETE_TIME
     *
     * @mbg.generated
     */
    public void setDeleteTime(Date deleteTime) {
        this.deleteTime = deleteTime;
    }
}