package wc.entity;

public class TbCrmRBusinessCustomer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_R_BUSINESS_CUSTOMER.ID
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_R_BUSINESS_CUSTOMER.BUSINESS_ID
     *
     * @mbg.generated
     */
    private Long businessId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_R_BUSINESS_CUSTOMER.CUSTOMER_ID
     *
     * @mbg.generated
     */
    private Long customerId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_R_BUSINESS_CUSTOMER.ID
     *
     * @return the value of TB_CRM_R_BUSINESS_CUSTOMER.ID
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_R_BUSINESS_CUSTOMER.ID
     *
     * @param id the value for TB_CRM_R_BUSINESS_CUSTOMER.ID
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_R_BUSINESS_CUSTOMER.BUSINESS_ID
     *
     * @return the value of TB_CRM_R_BUSINESS_CUSTOMER.BUSINESS_ID
     *
     * @mbg.generated
     */
    public Long getBusinessId() {
        return businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_R_BUSINESS_CUSTOMER.BUSINESS_ID
     *
     * @param businessId the value for TB_CRM_R_BUSINESS_CUSTOMER.BUSINESS_ID
     *
     * @mbg.generated
     */
    public void setBusinessId(Long businessId) {
        this.businessId = businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_R_BUSINESS_CUSTOMER.CUSTOMER_ID
     *
     * @return the value of TB_CRM_R_BUSINESS_CUSTOMER.CUSTOMER_ID
     *
     * @mbg.generated
     */
    public Long getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_R_BUSINESS_CUSTOMER.CUSTOMER_ID
     *
     * @param customerId the value for TB_CRM_R_BUSINESS_CUSTOMER.CUSTOMER_ID
     *
     * @mbg.generated
     */
    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }
}