package wc.entity;

import java.util.Date;

public class TbCrmEmailRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_EMAIL_RECORD.ID
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_EMAIL_RECORD.USER_ID
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_EMAIL_RECORD.TO_ADDR
     *
     * @mbg.generated
     */
    private String toAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_EMAIL_RECORD.SUBJECT
     *
     * @mbg.generated
     */
    private String subject;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_EMAIL_RECORD.ENDTIME
     *
     * @mbg.generated
     */
    private String endtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_EMAIL_RECORD.STATUS
     *
     * @mbg.generated
     */
    private Short status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_EMAIL_RECORD.CONTENT
     *
     * @mbg.generated
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_EMAIL_RECORD.ID
     *
     * @return the value of TB_CRM_EMAIL_RECORD.ID
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_EMAIL_RECORD.ID
     *
     * @param id the value for TB_CRM_EMAIL_RECORD.ID
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_EMAIL_RECORD.USER_ID
     *
     * @return the value of TB_CRM_EMAIL_RECORD.USER_ID
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_EMAIL_RECORD.USER_ID
     *
     * @param userId the value for TB_CRM_EMAIL_RECORD.USER_ID
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_EMAIL_RECORD.TO_ADDR
     *
     * @return the value of TB_CRM_EMAIL_RECORD.TO_ADDR
     *
     * @mbg.generated
     */
    public String getToAddr() {
        return toAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_EMAIL_RECORD.TO_ADDR
     *
     * @param toAddr the value for TB_CRM_EMAIL_RECORD.TO_ADDR
     *
     * @mbg.generated
     */
    public void setToAddr(String toAddr) {
        this.toAddr = toAddr == null ? null : toAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_EMAIL_RECORD.SUBJECT
     *
     * @return the value of TB_CRM_EMAIL_RECORD.SUBJECT
     *
     * @mbg.generated
     */
    public String getSubject() {
        return subject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_EMAIL_RECORD.SUBJECT
     *
     * @param subject the value for TB_CRM_EMAIL_RECORD.SUBJECT
     *
     * @mbg.generated
     */
    public void setSubject(String subject) {
        this.subject = subject == null ? null : subject.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_EMAIL_RECORD.ENDTIME
     *
     * @return the value of TB_CRM_EMAIL_RECORD.ENDTIME
     *
     * @mbg.generated
     */
    public String getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_EMAIL_RECORD.ENDTIME
     *
     * @param endtime the value for TB_CRM_EMAIL_RECORD.ENDTIME
     *
     * @mbg.generated
     */
    public void setEndtime(String endtime) {
        this.endtime = endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_EMAIL_RECORD.STATUS
     *
     * @return the value of TB_CRM_EMAIL_RECORD.STATUS
     *
     * @mbg.generated
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_EMAIL_RECORD.STATUS
     *
     * @param status the value for TB_CRM_EMAIL_RECORD.STATUS
     *
     * @mbg.generated
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_EMAIL_RECORD.CONTENT
     *
     * @return the value of TB_CRM_EMAIL_RECORD.CONTENT
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_EMAIL_RECORD.CONTENT
     *
     * @param content the value for TB_CRM_EMAIL_RECORD.CONTENT
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}