package wc.entity;

public class TbCrmBusinessStatus {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_BUSINESS_STATUS.ID
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_BUSINESS_STATUS.NAME
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_BUSINESS_STATUS.ORDER_ID
     *
     * @mbg.generated
     */
    private Long orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_BUSINESS_STATUS.IS_END
     *
     * @mbg.generated
     */
    private Short isEnd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_BUSINESS_STATUS.DESCRIPTION
     *
     * @mbg.generated
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_BUSINESS_STATUS.ID
     *
     * @return the value of TB_CRM_BUSINESS_STATUS.ID
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_BUSINESS_STATUS.ID
     *
     * @param id the value for TB_CRM_BUSINESS_STATUS.ID
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_BUSINESS_STATUS.NAME
     *
     * @return the value of TB_CRM_BUSINESS_STATUS.NAME
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_BUSINESS_STATUS.NAME
     *
     * @param name the value for TB_CRM_BUSINESS_STATUS.NAME
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_BUSINESS_STATUS.ORDER_ID
     *
     * @return the value of TB_CRM_BUSINESS_STATUS.ORDER_ID
     *
     * @mbg.generated
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_BUSINESS_STATUS.ORDER_ID
     *
     * @param orderId the value for TB_CRM_BUSINESS_STATUS.ORDER_ID
     *
     * @mbg.generated
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_BUSINESS_STATUS.IS_END
     *
     * @return the value of TB_CRM_BUSINESS_STATUS.IS_END
     *
     * @mbg.generated
     */
    public Short getIsEnd() {
        return isEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_BUSINESS_STATUS.IS_END
     *
     * @param isEnd the value for TB_CRM_BUSINESS_STATUS.IS_END
     *
     * @mbg.generated
     */
    public void setIsEnd(Short isEnd) {
        this.isEnd = isEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_BUSINESS_STATUS.DESCRIPTION
     *
     * @return the value of TB_CRM_BUSINESS_STATUS.DESCRIPTION
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_BUSINESS_STATUS.DESCRIPTION
     *
     * @param description the value for TB_CRM_BUSINESS_STATUS.DESCRIPTION
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}