package wc.entity;

public class TbCrmRBusinessContract {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_R_BUSINESS_CONTRACT.ID
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_R_BUSINESS_CONTRACT.BUSINESS_ID
     *
     * @mbg.generated
     */
    private Long businessId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_R_BUSINESS_CONTRACT.CONTRACT_ID
     *
     * @mbg.generated
     */
    private Long contractId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_R_BUSINESS_CONTRACT.ID
     *
     * @return the value of TB_CRM_R_BUSINESS_CONTRACT.ID
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_R_BUSINESS_CONTRACT.ID
     *
     * @param id the value for TB_CRM_R_BUSINESS_CONTRACT.ID
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_R_BUSINESS_CONTRACT.BUSINESS_ID
     *
     * @return the value of TB_CRM_R_BUSINESS_CONTRACT.BUSINESS_ID
     *
     * @mbg.generated
     */
    public Long getBusinessId() {
        return businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_R_BUSINESS_CONTRACT.BUSINESS_ID
     *
     * @param businessId the value for TB_CRM_R_BUSINESS_CONTRACT.BUSINESS_ID
     *
     * @mbg.generated
     */
    public void setBusinessId(Long businessId) {
        this.businessId = businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_R_BUSINESS_CONTRACT.CONTRACT_ID
     *
     * @return the value of TB_CRM_R_BUSINESS_CONTRACT.CONTRACT_ID
     *
     * @mbg.generated
     */
    public Long getContractId() {
        return contractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_R_BUSINESS_CONTRACT.CONTRACT_ID
     *
     * @param contractId the value for TB_CRM_R_BUSINESS_CONTRACT.CONTRACT_ID
     *
     * @mbg.generated
     */
    public void setContractId(Long contractId) {
        this.contractId = contractId;
    }
}