package wc.entity;

import java.math.BigDecimal;
import java.util.Date;

import com.fasterxml.jackson.annotation.JsonFormat;

public class TbCrmContract {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_CONTRACT.ID
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_CONTRACT.number
     *
     * @mbg.generated
     */
    private String number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_CONTRACT.BUSINESS_ID
     *
     * @mbg.generated
     */
    private Long businessId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_CONTRACT.PRICE
     *
     * @mbg.generated
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_CONTRACT.DUC_TIME
     *
     * @mbg.generated
     */
    @JsonFormat(pattern="yyyy-MM-dd HH-mm-ss")
    private String ducTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_CONTRACT.OWNER_USER_ID
     *
     * @mbg.generated
     */
    private Long ownerUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_CONTRACT.CREATOR_USER_ID
     *
     * @mbg.generated
     */
    private Long creatorUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_CONTRACT.DESCRIPTION
     *
     * @mbg.generated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_CONTRACT.CREATE_TIME
     *
     * @mbg.generated
     */
    @JsonFormat(pattern="yyyy-MM-dd HH-mm-ss")
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_CONTRACT.UPDATE_TIME
     *
     * @mbg.generated
     */
    @JsonFormat(pattern="yyyy-MM-dd HH-mm-ss")
    private String updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_CONTRACT.START_DATE
     *
     * @mbg.generated
     */
    @JsonFormat(pattern="yyyy-MM-dd HH-mm-ss")
    private String startDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_CONTRACT.END_DATE
     *
     * @mbg.generated
     */
    @JsonFormat(pattern="yyyy-MM-dd HH-mm-ss")
    private String endDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_CONTRACT.STATUS
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_CONTRACT.DELETE_STATUS
     *
     * @mbg.generated
     */
    private Short deleteStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_CONTRACT.DELETE_USER_ID
     *
     * @mbg.generated
     */
    private Long deleteUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_CONTRACT.DELETE_TIME
     *
     * @mbg.generated
     */
    @JsonFormat(pattern="yyyy-MM-dd HH-mm-ss")
    private String deleteTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_CONTRACT.CONTENT
     *
     * @mbg.generated
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_CONTRACT.ID
     *
     * @return the value of TB_CRM_CONTRACT.ID
     *
     * @mbg.generated
     */
   
	@Override
	public String toString() {
		return "TbCrmContract [id=" + id + ", number=" + number + ", businessId=" + businessId + ", price=" + price
				+ ", ducTime=" + ducTime + ", ownerUserId=" + ownerUserId + ", creatorUserId=" + creatorUserId
				+ ", description=" + description + ", createTime=" + createTime + ", updateTime=" + updateTime
				+ ", startDate=" + startDate + ", endDate=" + endDate + ", status=" + status + ", deleteStatus="
				+ deleteStatus + ", deleteUserId=" + deleteUserId + ", deleteTime=" + deleteTime + ", content="
				+ content + "]";
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getNumber() {
		return number;
	}

	public void setNumber(String number) {
		this.number = number;
	}

	public Long getBusinessId() {
		return businessId;
	}

	public void setBusinessId(Long businessId) {
		this.businessId = businessId;
	}

	public BigDecimal getPrice() {
		return price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	public String getDucTime() {
		return ducTime;
	}

	public void setDucTime(String ducTime) {
		this.ducTime = ducTime;
	}

	public Long getOwnerUserId() {
		return ownerUserId;
	}

	public void setOwnerUserId(Long ownerUserId) {
		this.ownerUserId = ownerUserId;
	}

	public Long getCreatorUserId() {
		return creatorUserId;
	}

	public void setCreatorUserId(Long creatorUserId) {
		this.creatorUserId = creatorUserId;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getCreateTime() {
		return createTime;
	}

	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}

	public String getUpdateTime() {
		return updateTime;
	}

	public void setUpdateTime(String updateTime) {
		this.updateTime = updateTime;
	}

	public String getStartDate() {
		return startDate;
	}

	public void setStartDate(String startDate) {
		this.startDate = startDate;
	}

	public String getEndDate() {
		return endDate;
	}

	public void setEndDate(String endDate) {
		this.endDate = endDate;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Short getDeleteStatus() {
		return deleteStatus;
	}

	public void setDeleteStatus(Short deleteStatus) {
		this.deleteStatus = deleteStatus;
	}

	public Long getDeleteUserId() {
		return deleteUserId;
	}

	public void setDeleteUserId(Long deleteUserId) {
		this.deleteUserId = deleteUserId;
	}

	public String getDeleteTime() {
		return deleteTime;
	}

	public void setDeleteTime(String deleteTime) {
		this.deleteTime = deleteTime;
	}

	public String getContent() {
		return content;
	}

	public void setContent(String content) {
		this.content = content;
	}
    
}