package wc.entity;

import java.util.Date;

public class TbCrmLeads {
	
	private Long day;
    public Long getDay() {
		return day;
	}

	public void setDay(Long day) {
		this.day = day;
	}

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_LEADS.ID
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_LEADS.OWNER_USER_ID
     *
     * @mbg.generated
     */
    private Long ownerUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_LEADS.CREATOR_USER_ID
     *
     * @mbg.generated
     */
    private Long creatorUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_LEADS.NAME
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_LEADS.POSITION
     *
     * @mbg.generated
     */
    private String position;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_LEADS.CONTACTS_NAME
     *
     * @mbg.generated
     */
    private String contactsName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_LEADS.SALTNAME
     *
     * @mbg.generated
     */
    private String saltname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_LEADS.MOBILE
     *
     * @mbg.generated
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_LEADS.EMAIL
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_LEADS.CREATE_TIME
     *
     * @mbg.generated
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_LEADS.UPDATE_TIME
     *
     * @mbg.generated
     */
    private String updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_LEADS.DELETE_STATUS
     *
     * @mbg.generated
     */
    private Short deleteStatus = 0;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_LEADS.DELETE_USER_ID
     *
     * @mbg.generated
     */
    private Short deleteUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_LEADS.DELETE_TIME
     *
     * @mbg.generated
     */
    private String deleteTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_LEADS.IS_TRANSFORMED
     *
     * @mbg.generated
     */
    private Short isTransformed = 0;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_LEADS.TRANSFORM_USER_ID
     *
     * @mbg.generated
     */
    private Long transformUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_LEADS.CONTACTS_ID
     *
     * @mbg.generated
     */
    private Long contactsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_LEADS.CUSTOMER_ID
     *
     * @mbg.generated
     */
    private Long customerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_LEADS.BUSINESS_ID
     *
     * @mbg.generated
     */
    private Long businessId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_LEADS.NEXTSTEP
     *
     * @mbg.generated
     */
    private String nextstep;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_LEADS.NEXTSTEP_TIME
     *
     * @mbg.generated
     */
    private String nextstepTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_LEADS.HAVE_TIME
     *
     * @mbg.generated
     */
    private String haveTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_LEADS.ADDRESS
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_LEADS.SOURCE
     *
     * @mbg.generated
     */
    private String source;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_LEADS.LEADNOTE
     *
     * @mbg.generated
     */
    private String leadnote;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_LEADS.ID
     *
     * @return the value of TB_CRM_LEADS.ID
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_LEADS.ID
     *
     * @param id the value for TB_CRM_LEADS.ID
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_LEADS.OWNER_USER_ID
     *
     * @return the value of TB_CRM_LEADS.OWNER_USER_ID
     *
     * @mbg.generated
     */
    public Long getOwnerUserId() {
        return ownerUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_LEADS.OWNER_USER_ID
     *
     * @param ownerUserId the value for TB_CRM_LEADS.OWNER_USER_ID
     *
     * @mbg.generated
     */
    public void setOwnerUserId(Long ownerUserId) {
        this.ownerUserId = ownerUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_LEADS.CREATOR_USER_ID
     *
     * @return the value of TB_CRM_LEADS.CREATOR_USER_ID
     *
     * @mbg.generated
     */
    public Long getCreatorUserId() {
        return creatorUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_LEADS.CREATOR_USER_ID
     *
     * @param creatorUserId the value for TB_CRM_LEADS.CREATOR_USER_ID
     *
     * @mbg.generated
     */
    public void setCreatorUserId(Long creatorUserId) {
        this.creatorUserId = creatorUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_LEADS.NAME
     *
     * @return the value of TB_CRM_LEADS.NAME
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_LEADS.NAME
     *
     * @param name the value for TB_CRM_LEADS.NAME
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_LEADS.POSITION
     *
     * @return the value of TB_CRM_LEADS.POSITION
     *
     * @mbg.generated
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_LEADS.POSITION
     *
     * @param position the value for TB_CRM_LEADS.POSITION
     *
     * @mbg.generated
     */
    public void setPosition(String position) {
        this.position = position == null ? null : position.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_LEADS.CONTACTS_NAME
     *
     * @return the value of TB_CRM_LEADS.CONTACTS_NAME
     *
     * @mbg.generated
     */
    public String getContactsName() {
        return contactsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_LEADS.CONTACTS_NAME
     *
     * @param contactsName the value for TB_CRM_LEADS.CONTACTS_NAME
     *
     * @mbg.generated
     */
    public void setContactsName(String contactsName) {
        this.contactsName = contactsName == null ? null : contactsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_LEADS.SALTNAME
     *
     * @return the value of TB_CRM_LEADS.SALTNAME
     *
     * @mbg.generated
     */
    public String getSaltname() {
        return saltname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_LEADS.SALTNAME
     *
     * @param saltname the value for TB_CRM_LEADS.SALTNAME
     *
     * @mbg.generated
     */
    public void setSaltname(String saltname) {
        this.saltname = saltname == null ? null : saltname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_LEADS.MOBILE
     *
     * @return the value of TB_CRM_LEADS.MOBILE
     *
     * @mbg.generated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_LEADS.MOBILE
     *
     * @param mobile the value for TB_CRM_LEADS.MOBILE
     *
     * @mbg.generated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_LEADS.EMAIL
     *
     * @return the value of TB_CRM_LEADS.EMAIL
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_LEADS.EMAIL
     *
     * @param email the value for TB_CRM_LEADS.EMAIL
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_LEADS.CREATE_TIME
     *
     * @return the value of TB_CRM_LEADS.CREATE_TIME
     *
     * @mbg.generated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_LEADS.CREATE_TIME
     *
     * @param createTime the value for TB_CRM_LEADS.CREATE_TIME
     *
     * @mbg.generated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_LEADS.UPDATE_TIME
     *
     * @return the value of TB_CRM_LEADS.UPDATE_TIME
     *
     * @mbg.generated
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_LEADS.UPDATE_TIME
     *
     * @param updateTime the value for TB_CRM_LEADS.UPDATE_TIME
     *
     * @mbg.generated
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_LEADS.DELETE_STATUS
     *
     * @return the value of TB_CRM_LEADS.DELETE_STATUS
     *
     * @mbg.generated
     */
    public Short getDeleteStatus() {
        return deleteStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_LEADS.DELETE_STATUS
     *
     * @param deleteStatus the value for TB_CRM_LEADS.DELETE_STATUS
     *
     * @mbg.generated
     */
    public void setDeleteStatus(Short deleteStatus) {
        this.deleteStatus = deleteStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_LEADS.DELETE_USER_ID
     *
     * @return the value of TB_CRM_LEADS.DELETE_USER_ID
     *
     * @mbg.generated
     */
    public Short getDeleteUserId() {
        return deleteUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_LEADS.DELETE_USER_ID
     *
     * @param deleteUserId the value for TB_CRM_LEADS.DELETE_USER_ID
     *
     * @mbg.generated
     */
    public void setDeleteUserId(Short deleteUserId) {
        this.deleteUserId = deleteUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_LEADS.DELETE_TIME
     *
     * @return the value of TB_CRM_LEADS.DELETE_TIME
     *
     * @mbg.generated
     */
    public String getDeleteTime() {
        return deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_LEADS.DELETE_TIME
     *
     * @param deleteTime the value for TB_CRM_LEADS.DELETE_TIME
     *
     * @mbg.generated
     */
    public void setDeleteTime(String deleteTime) {
        this.deleteTime = deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_LEADS.IS_TRANSFORMED
     *
     * @return the value of TB_CRM_LEADS.IS_TRANSFORMED
     *
     * @mbg.generated
     */
    public Short getIsTransformed() {
        return isTransformed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_LEADS.IS_TRANSFORMED
     *
     * @param isTransformed the value for TB_CRM_LEADS.IS_TRANSFORMED
     *
     * @mbg.generated
     */
    public void setIsTransformed(Short isTransformed) {
        this.isTransformed = isTransformed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_LEADS.TRANSFORM_USER_ID
     *
     * @return the value of TB_CRM_LEADS.TRANSFORM_USER_ID
     *
     * @mbg.generated
     */
    public Long getTransformUserId() {
        return transformUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_LEADS.TRANSFORM_USER_ID
     *
     * @param transformUserId the value for TB_CRM_LEADS.TRANSFORM_USER_ID
     *
     * @mbg.generated
     */
    public void setTransformUserId(Long transformUserId) {
        this.transformUserId = transformUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_LEADS.CONTACTS_ID
     *
     * @return the value of TB_CRM_LEADS.CONTACTS_ID
     *
     * @mbg.generated
     */
    public Long getContactsId() {
        return contactsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_LEADS.CONTACTS_ID
     *
     * @param contactsId the value for TB_CRM_LEADS.CONTACTS_ID
     *
     * @mbg.generated
     */
    public void setContactsId(Long contactsId) {
        this.contactsId = contactsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_LEADS.CUSTOMER_ID
     *
     * @return the value of TB_CRM_LEADS.CUSTOMER_ID
     *
     * @mbg.generated
     */
    public Long getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_LEADS.CUSTOMER_ID
     *
     * @param customerId the value for TB_CRM_LEADS.CUSTOMER_ID
     *
     * @mbg.generated
     */
    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_LEADS.BUSINESS_ID
     *
     * @return the value of TB_CRM_LEADS.BUSINESS_ID
     *
     * @mbg.generated
     */
    public Long getBusinessId() {
        return businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_LEADS.BUSINESS_ID
     *
     * @param businessId the value for TB_CRM_LEADS.BUSINESS_ID
     *
     * @mbg.generated
     */
    public void setBusinessId(Long businessId) {
        this.businessId = businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_LEADS.NEXTSTEP
     *
     * @return the value of TB_CRM_LEADS.NEXTSTEP
     *
     * @mbg.generated
     */
    public String getNextstep() {
        return nextstep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_LEADS.NEXTSTEP
     *
     * @param nextstep the value for TB_CRM_LEADS.NEXTSTEP
     *
     * @mbg.generated
     */
    public void setNextstep(String nextstep) {
        this.nextstep = nextstep == null ? null : nextstep.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_LEADS.NEXTSTEP_TIME
     *
     * @return the value of TB_CRM_LEADS.NEXTSTEP_TIME
     *
     * @mbg.generated
     */
    public String getNextstepTime() {
        return nextstepTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_LEADS.NEXTSTEP_TIME
     *
     * @param nextstepTime the value for TB_CRM_LEADS.NEXTSTEP_TIME
     *
     * @mbg.generated
     */
    public void setNextstepTime(String nextstepTime) {
        this.nextstepTime = nextstepTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_LEADS.HAVE_TIME
     *
     * @return the value of TB_CRM_LEADS.HAVE_TIME
     *
     * @mbg.generated
     */
    public String getHaveTime() {
        return haveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_LEADS.HAVE_TIME
     *
     * @param haveTime the value for TB_CRM_LEADS.HAVE_TIME
     *
     * @mbg.generated
     */
    public void setHaveTime(String haveTime) {
        this.haveTime = haveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_LEADS.ADDRESS
     *
     * @return the value of TB_CRM_LEADS.ADDRESS
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_LEADS.ADDRESS
     *
     * @param address the value for TB_CRM_LEADS.ADDRESS
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_LEADS.SOURCE
     *
     * @return the value of TB_CRM_LEADS.SOURCE
     *
     * @mbg.generated
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_LEADS.SOURCE
     *
     * @param source the value for TB_CRM_LEADS.SOURCE
     *
     * @mbg.generated
     */
    public void setSource(String source) {
        this.source = source == null ? null : source.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_LEADS.LEADNOTE
     *
     * @return the value of TB_CRM_LEADS.LEADNOTE
     *
     * @mbg.generated
     */
    public String getLeadnote() {
        return leadnote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_LEADS.LEADNOTE
     *
     * @param leadnote the value for TB_CRM_LEADS.LEADNOTE
     *
     * @mbg.generated
     */
    public void setLeadnote(String leadnote) {
        this.leadnote = leadnote == null ? null : leadnote.trim();
    }

	@Override
	public String toString() {
		return "TbCrmLeads [day=" + day + ", id=" + id + ", ownerUserId=" + ownerUserId + ", creatorUserId="
				+ creatorUserId + ", name=" + name + ", position=" + position + ", contactsName=" + contactsName
				+ ", saltname=" + saltname + ", mobile=" + mobile + ", email=" + email + ", createTime=" + createTime
				+ ", updateTime=" + updateTime + ", deleteStatus=" + deleteStatus + ", deleteUserId=" + deleteUserId
				+ ", deleteTime=" + deleteTime + ", isTransformed=" + isTransformed + ", transformUserId="
				+ transformUserId + ", contactsId=" + contactsId + ", customerId=" + customerId + ", businessId="
				+ businessId + ", nextstep=" + nextstep + ", nextstepTime=" + nextstepTime + ", haveTime=" + haveTime
				+ ", address=" + address + ", source=" + source + ", leadnote=" + leadnote + "]";
	}
    
    
}