package wc.entity;

import java.math.BigDecimal;

public class TbCrmRBusinessProduct {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_R_BUSINESS_PRODUCT.ID
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_R_BUSINESS_PRODUCT.BUSINESS_ID
     *
     * @mbg.generated
     */
    private Long businessId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_R_BUSINESS_PRODUCT.PRODUCT_ID
     *
     * @mbg.generated
     */
    private Long productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_R_BUSINESS_PRODUCT.SALES_PRICE
     *
     * @mbg.generated
     */
    private BigDecimal salesPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_R_BUSINESS_PRODUCT.ESTIMATE_PRICE
     *
     * @mbg.generated
     */
    private BigDecimal estimatePrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_R_BUSINESS_PRODUCT.AMOUNT
     *
     * @mbg.generated
     */
    private Long amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_R_BUSINESS_PRODUCT.DISCOUNT_RATE
     *
     * @mbg.generated
     */
    private Short discountRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_R_BUSINESS_PRODUCT.TAX_RATE
     *
     * @mbg.generated
     */
    private Short taxRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_R_BUSINESS_PRODUCT.UNIT_PRICE
     *
     * @mbg.generated
     */
    private BigDecimal unitPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_R_BUSINESS_PRODUCT.SUBTOTAL
     *
     * @mbg.generated
     */
    private BigDecimal subtotal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_R_BUSINESS_PRODUCT.DESCRIPTION
     *
     * @mbg.generated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_R_BUSINESS_PRODUCT.SUBTOTAL_VAL
     *
     * @mbg.generated
     */
    private BigDecimal subtotalVal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_R_BUSINESS_PRODUCT.DISCOUNT_PRICE
     *
     * @mbg.generated
     */
    private BigDecimal discountPrice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_R_BUSINESS_PRODUCT.ID
     *
     * @return the value of TB_CRM_R_BUSINESS_PRODUCT.ID
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_R_BUSINESS_PRODUCT.ID
     *
     * @param id the value for TB_CRM_R_BUSINESS_PRODUCT.ID
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_R_BUSINESS_PRODUCT.BUSINESS_ID
     *
     * @return the value of TB_CRM_R_BUSINESS_PRODUCT.BUSINESS_ID
     *
     * @mbg.generated
     */
    public Long getBusinessId() {
        return businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_R_BUSINESS_PRODUCT.BUSINESS_ID
     *
     * @param businessId the value for TB_CRM_R_BUSINESS_PRODUCT.BUSINESS_ID
     *
     * @mbg.generated
     */
    public void setBusinessId(Long businessId) {
        this.businessId = businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_R_BUSINESS_PRODUCT.PRODUCT_ID
     *
     * @return the value of TB_CRM_R_BUSINESS_PRODUCT.PRODUCT_ID
     *
     * @mbg.generated
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_R_BUSINESS_PRODUCT.PRODUCT_ID
     *
     * @param productId the value for TB_CRM_R_BUSINESS_PRODUCT.PRODUCT_ID
     *
     * @mbg.generated
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_R_BUSINESS_PRODUCT.SALES_PRICE
     *
     * @return the value of TB_CRM_R_BUSINESS_PRODUCT.SALES_PRICE
     *
     * @mbg.generated
     */
    public BigDecimal getSalesPrice() {
        return salesPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_R_BUSINESS_PRODUCT.SALES_PRICE
     *
     * @param salesPrice the value for TB_CRM_R_BUSINESS_PRODUCT.SALES_PRICE
     *
     * @mbg.generated
     */
    public void setSalesPrice(BigDecimal salesPrice) {
        this.salesPrice = salesPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_R_BUSINESS_PRODUCT.ESTIMATE_PRICE
     *
     * @return the value of TB_CRM_R_BUSINESS_PRODUCT.ESTIMATE_PRICE
     *
     * @mbg.generated
     */
    public BigDecimal getEstimatePrice() {
        return estimatePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_R_BUSINESS_PRODUCT.ESTIMATE_PRICE
     *
     * @param estimatePrice the value for TB_CRM_R_BUSINESS_PRODUCT.ESTIMATE_PRICE
     *
     * @mbg.generated
     */
    public void setEstimatePrice(BigDecimal estimatePrice) {
        this.estimatePrice = estimatePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_R_BUSINESS_PRODUCT.AMOUNT
     *
     * @return the value of TB_CRM_R_BUSINESS_PRODUCT.AMOUNT
     *
     * @mbg.generated
     */
    public Long getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_R_BUSINESS_PRODUCT.AMOUNT
     *
     * @param amount the value for TB_CRM_R_BUSINESS_PRODUCT.AMOUNT
     *
     * @mbg.generated
     */
    public void setAmount(Long amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_R_BUSINESS_PRODUCT.DISCOUNT_RATE
     *
     * @return the value of TB_CRM_R_BUSINESS_PRODUCT.DISCOUNT_RATE
     *
     * @mbg.generated
     */
    public Short getDiscountRate() {
        return discountRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_R_BUSINESS_PRODUCT.DISCOUNT_RATE
     *
     * @param discountRate the value for TB_CRM_R_BUSINESS_PRODUCT.DISCOUNT_RATE
     *
     * @mbg.generated
     */
    public void setDiscountRate(Short discountRate) {
        this.discountRate = discountRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_R_BUSINESS_PRODUCT.TAX_RATE
     *
     * @return the value of TB_CRM_R_BUSINESS_PRODUCT.TAX_RATE
     *
     * @mbg.generated
     */
    public Short getTaxRate() {
        return taxRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_R_BUSINESS_PRODUCT.TAX_RATE
     *
     * @param taxRate the value for TB_CRM_R_BUSINESS_PRODUCT.TAX_RATE
     *
     * @mbg.generated
     */
    public void setTaxRate(Short taxRate) {
        this.taxRate = taxRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_R_BUSINESS_PRODUCT.UNIT_PRICE
     *
     * @return the value of TB_CRM_R_BUSINESS_PRODUCT.UNIT_PRICE
     *
     * @mbg.generated
     */
    public BigDecimal getUnitPrice() {
        return unitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_R_BUSINESS_PRODUCT.UNIT_PRICE
     *
     * @param unitPrice the value for TB_CRM_R_BUSINESS_PRODUCT.UNIT_PRICE
     *
     * @mbg.generated
     */
    public void setUnitPrice(BigDecimal unitPrice) {
        this.unitPrice = unitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_R_BUSINESS_PRODUCT.SUBTOTAL
     *
     * @return the value of TB_CRM_R_BUSINESS_PRODUCT.SUBTOTAL
     *
     * @mbg.generated
     */
    public BigDecimal getSubtotal() {
        return subtotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_R_BUSINESS_PRODUCT.SUBTOTAL
     *
     * @param subtotal the value for TB_CRM_R_BUSINESS_PRODUCT.SUBTOTAL
     *
     * @mbg.generated
     */
    public void setSubtotal(BigDecimal subtotal) {
        this.subtotal = subtotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_R_BUSINESS_PRODUCT.DESCRIPTION
     *
     * @return the value of TB_CRM_R_BUSINESS_PRODUCT.DESCRIPTION
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_R_BUSINESS_PRODUCT.DESCRIPTION
     *
     * @param description the value for TB_CRM_R_BUSINESS_PRODUCT.DESCRIPTION
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_R_BUSINESS_PRODUCT.SUBTOTAL_VAL
     *
     * @return the value of TB_CRM_R_BUSINESS_PRODUCT.SUBTOTAL_VAL
     *
     * @mbg.generated
     */
    public BigDecimal getSubtotalVal() {
        return subtotalVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_R_BUSINESS_PRODUCT.SUBTOTAL_VAL
     *
     * @param subtotalVal the value for TB_CRM_R_BUSINESS_PRODUCT.SUBTOTAL_VAL
     *
     * @mbg.generated
     */
    public void setSubtotalVal(BigDecimal subtotalVal) {
        this.subtotalVal = subtotalVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_R_BUSINESS_PRODUCT.DISCOUNT_PRICE
     *
     * @return the value of TB_CRM_R_BUSINESS_PRODUCT.DISCOUNT_PRICE
     *
     * @mbg.generated
     */
    public BigDecimal getDiscountPrice() {
        return discountPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_R_BUSINESS_PRODUCT.DISCOUNT_PRICE
     *
     * @param discountPrice the value for TB_CRM_R_BUSINESS_PRODUCT.DISCOUNT_PRICE
     *
     * @mbg.generated
     */
    public void setDiscountPrice(BigDecimal discountPrice) {
        this.discountPrice = discountPrice;
    }
}