package wc.entity;

import java.util.Date;

public class TbCrmCustomer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_CUSTOMER.ID
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_CUSTOMER.OWNER_USER_ID
     *
     * @mbg.generated
     */
    private Long ownerUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_CUSTOMER.CREATOR_USER_ID
     *
     * @mbg.generated
     */
    private Long creatorUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_CUSTOMER.NAME
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_CUSTOMER.ORIGIN
     *
     * @mbg.generated
     */
    private String origin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_CUSTOMER.ADDRESS
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_CUSTOMER.ZIP_CODE
     *
     * @mbg.generated
     */
    private String zipCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_CUSTOMER.INDUSTRY
     *
     * @mbg.generated
     */
    private String industry;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_CUSTOMER.ANNUAL_REVENUE
     *
     * @mbg.generated
     */
    private String annualRevenue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_CUSTOMER.OWNERSHIP
     *
     * @mbg.generated
     */
    private String ownership;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_CUSTOMER.RATING
     *
     * @mbg.generated
     */
    private String rating;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_CUSTOMER.CREATE_TIME
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_CUSTOMER.UPDATE_TIME
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_CUSTOMER.DELETE_STATUS
     *
     * @mbg.generated
     */
    private Short deleteStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_CUSTOMER.IS_LOCKED
     *
     * @mbg.generated
     */
    private Short isLocked;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_CUSTOMER.DELETE_USER_ID
     *
     * @mbg.generated
     */
    private Long deleteUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_CUSTOMER.DELETE_TIME
     *
     * @mbg.generated
     */
    private Date deleteTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_CUSTOMER.ID
     *
     * @return the value of TB_CRM_CUSTOMER.ID
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_CUSTOMER.ID
     *
     * @param id the value for TB_CRM_CUSTOMER.ID
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_CUSTOMER.OWNER_USER_ID
     *
     * @return the value of TB_CRM_CUSTOMER.OWNER_USER_ID
     *
     * @mbg.generated
     */
    public Long getOwnerUserId() {
        return ownerUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_CUSTOMER.OWNER_USER_ID
     *
     * @param ownerUserId the value for TB_CRM_CUSTOMER.OWNER_USER_ID
     *
     * @mbg.generated
     */
    public void setOwnerUserId(Long ownerUserId) {
        this.ownerUserId = ownerUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_CUSTOMER.CREATOR_USER_ID
     *
     * @return the value of TB_CRM_CUSTOMER.CREATOR_USER_ID
     *
     * @mbg.generated
     */
    public Long getCreatorUserId() {
        return creatorUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_CUSTOMER.CREATOR_USER_ID
     *
     * @param creatorUserId the value for TB_CRM_CUSTOMER.CREATOR_USER_ID
     *
     * @mbg.generated
     */
    public void setCreatorUserId(Long creatorUserId) {
        this.creatorUserId = creatorUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_CUSTOMER.NAME
     *
     * @return the value of TB_CRM_CUSTOMER.NAME
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_CUSTOMER.NAME
     *
     * @param name the value for TB_CRM_CUSTOMER.NAME
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_CUSTOMER.ORIGIN
     *
     * @return the value of TB_CRM_CUSTOMER.ORIGIN
     *
     * @mbg.generated
     */
    public String getOrigin() {
        return origin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_CUSTOMER.ORIGIN
     *
     * @param origin the value for TB_CRM_CUSTOMER.ORIGIN
     *
     * @mbg.generated
     */
    public void setOrigin(String origin) {
        this.origin = origin == null ? null : origin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_CUSTOMER.ADDRESS
     *
     * @return the value of TB_CRM_CUSTOMER.ADDRESS
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_CUSTOMER.ADDRESS
     *
     * @param address the value for TB_CRM_CUSTOMER.ADDRESS
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_CUSTOMER.ZIP_CODE
     *
     * @return the value of TB_CRM_CUSTOMER.ZIP_CODE
     *
     * @mbg.generated
     */
    public String getZipCode() {
        return zipCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_CUSTOMER.ZIP_CODE
     *
     * @param zipCode the value for TB_CRM_CUSTOMER.ZIP_CODE
     *
     * @mbg.generated
     */
    public void setZipCode(String zipCode) {
        this.zipCode = zipCode == null ? null : zipCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_CUSTOMER.INDUSTRY
     *
     * @return the value of TB_CRM_CUSTOMER.INDUSTRY
     *
     * @mbg.generated
     */
    public String getIndustry() {
        return industry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_CUSTOMER.INDUSTRY
     *
     * @param industry the value for TB_CRM_CUSTOMER.INDUSTRY
     *
     * @mbg.generated
     */
    public void setIndustry(String industry) {
        this.industry = industry == null ? null : industry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_CUSTOMER.ANNUAL_REVENUE
     *
     * @return the value of TB_CRM_CUSTOMER.ANNUAL_REVENUE
     *
     * @mbg.generated
     */
    public String getAnnualRevenue() {
        return annualRevenue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_CUSTOMER.ANNUAL_REVENUE
     *
     * @param annualRevenue the value for TB_CRM_CUSTOMER.ANNUAL_REVENUE
     *
     * @mbg.generated
     */
    public void setAnnualRevenue(String annualRevenue) {
        this.annualRevenue = annualRevenue == null ? null : annualRevenue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_CUSTOMER.OWNERSHIP
     *
     * @return the value of TB_CRM_CUSTOMER.OWNERSHIP
     *
     * @mbg.generated
     */
    public String getOwnership() {
        return ownership;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_CUSTOMER.OWNERSHIP
     *
     * @param ownership the value for TB_CRM_CUSTOMER.OWNERSHIP
     *
     * @mbg.generated
     */
    public void setOwnership(String ownership) {
        this.ownership = ownership == null ? null : ownership.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_CUSTOMER.RATING
     *
     * @return the value of TB_CRM_CUSTOMER.RATING
     *
     * @mbg.generated
     */
    public String getRating() {
        return rating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_CUSTOMER.RATING
     *
     * @param rating the value for TB_CRM_CUSTOMER.RATING
     *
     * @mbg.generated
     */
    public void setRating(String rating) {
        this.rating = rating == null ? null : rating.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_CUSTOMER.CREATE_TIME
     *
     * @return the value of TB_CRM_CUSTOMER.CREATE_TIME
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_CUSTOMER.CREATE_TIME
     *
     * @param createTime the value for TB_CRM_CUSTOMER.CREATE_TIME
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_CUSTOMER.UPDATE_TIME
     *
     * @return the value of TB_CRM_CUSTOMER.UPDATE_TIME
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_CUSTOMER.UPDATE_TIME
     *
     * @param updateTime the value for TB_CRM_CUSTOMER.UPDATE_TIME
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_CUSTOMER.DELETE_STATUS
     *
     * @return the value of TB_CRM_CUSTOMER.DELETE_STATUS
     *
     * @mbg.generated
     */
    public Short getDeleteStatus() {
        return deleteStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_CUSTOMER.DELETE_STATUS
     *
     * @param deleteStatus the value for TB_CRM_CUSTOMER.DELETE_STATUS
     *
     * @mbg.generated
     */
    public void setDeleteStatus(Short deleteStatus) {
        this.deleteStatus = deleteStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_CUSTOMER.IS_LOCKED
     *
     * @return the value of TB_CRM_CUSTOMER.IS_LOCKED
     *
     * @mbg.generated
     */
    public Short getIsLocked() {
        return isLocked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_CUSTOMER.IS_LOCKED
     *
     * @param isLocked the value for TB_CRM_CUSTOMER.IS_LOCKED
     *
     * @mbg.generated
     */
    public void setIsLocked(Short isLocked) {
        this.isLocked = isLocked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_CUSTOMER.DELETE_USER_ID
     *
     * @return the value of TB_CRM_CUSTOMER.DELETE_USER_ID
     *
     * @mbg.generated
     */
    public Long getDeleteUserId() {
        return deleteUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_CUSTOMER.DELETE_USER_ID
     *
     * @param deleteUserId the value for TB_CRM_CUSTOMER.DELETE_USER_ID
     *
     * @mbg.generated
     */
    public void setDeleteUserId(Long deleteUserId) {
        this.deleteUserId = deleteUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_CUSTOMER.DELETE_TIME
     *
     * @return the value of TB_CRM_CUSTOMER.DELETE_TIME
     *
     * @mbg.generated
     */
    public Date getDeleteTime() {
        return deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_CUSTOMER.DELETE_TIME
     *
     * @param deleteTime the value for TB_CRM_CUSTOMER.DELETE_TIME
     *
     * @mbg.generated
     */
    public void setDeleteTime(Date deleteTime) {
        this.deleteTime = deleteTime;
    }
}