package wc.entity;

public class TbCrmDepartment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_DEPARTMENT.ID
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_DEPARTMENT.PARENT_ID
     *
     * @mbg.generated
     */
    private Long parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_DEPARTMENT.NAME
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_DEPARTMENT.DESCRIPTION
     *
     * @mbg.generated
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_DEPARTMENT.ID
     *
     * @return the value of TB_CRM_DEPARTMENT.ID
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_DEPARTMENT.ID
     *
     * @param id the value for TB_CRM_DEPARTMENT.ID
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_DEPARTMENT.PARENT_ID
     *
     * @return the value of TB_CRM_DEPARTMENT.PARENT_ID
     *
     * @mbg.generated
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_DEPARTMENT.PARENT_ID
     *
     * @param parentId the value for TB_CRM_DEPARTMENT.PARENT_ID
     *
     * @mbg.generated
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_DEPARTMENT.NAME
     *
     * @return the value of TB_CRM_DEPARTMENT.NAME
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_DEPARTMENT.NAME
     *
     * @param name the value for TB_CRM_DEPARTMENT.NAME
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_DEPARTMENT.DESCRIPTION
     *
     * @return the value of TB_CRM_DEPARTMENT.DESCRIPTION
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_DEPARTMENT.DESCRIPTION
     *
     * @param description the value for TB_CRM_DEPARTMENT.DESCRIPTION
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

	@Override
	public String toString() {
		return "TbCrmDepartment [id=" + id + ", parentId=" + parentId + ", name=" + name + ", description="
				+ description + "]";
	}
    
}