package wc.entity;

import java.util.Date;

public class TbCrmEmployee {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_EMPLOYEE.ID
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_EMPLOYEE.POSITION_ID
     *
     * @mbg.generated
     */
    private Long positionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_EMPLOYEE.STATUS
     *
     * @mbg.generated
     */
    private Short status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_EMPLOYEE.NAME
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_EMPLOYEE.IMG
     *
     * @mbg.generated
     */
    private String img;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_EMPLOYEE.SEX
     *
     * @mbg.generated
     */
    private Short sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_EMPLOYEE.EMAIL
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_EMPLOYEE.TELEPHONE
     *
     * @mbg.generated
     */
    private String telephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_EMPLOYEE.ADDRESS
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_EMPLOYEE.CREATE_TIME
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_EMPLOYEE.CREATE_USER_ID
     *
     * @mbg.generated
     */
    private Long createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_EMPLOYEE.UPDATE_TIME
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_EMPLOYEE.UPDATE_USER_ID
     *
     * @mbg.generated
     */
    private Long updateUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_EMPLOYEE.USER_ID
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_EMPLOYEE.ID
     *
     * @return the value of TB_CRM_EMPLOYEE.ID
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_EMPLOYEE.ID
     *
     * @param id the value for TB_CRM_EMPLOYEE.ID
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_EMPLOYEE.POSITION_ID
     *
     * @return the value of TB_CRM_EMPLOYEE.POSITION_ID
     *
     * @mbg.generated
     */
    public Long getPositionId() {
        return positionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_EMPLOYEE.POSITION_ID
     *
     * @param positionId the value for TB_CRM_EMPLOYEE.POSITION_ID
     *
     * @mbg.generated
     */
    public void setPositionId(Long positionId) {
        this.positionId = positionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_EMPLOYEE.STATUS
     *
     * @return the value of TB_CRM_EMPLOYEE.STATUS
     *
     * @mbg.generated
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_EMPLOYEE.STATUS
     *
     * @param status the value for TB_CRM_EMPLOYEE.STATUS
     *
     * @mbg.generated
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_EMPLOYEE.NAME
     *
     * @return the value of TB_CRM_EMPLOYEE.NAME
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_EMPLOYEE.NAME
     *
     * @param name the value for TB_CRM_EMPLOYEE.NAME
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_EMPLOYEE.IMG
     *
     * @return the value of TB_CRM_EMPLOYEE.IMG
     *
     * @mbg.generated
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_EMPLOYEE.IMG
     *
     * @param img the value for TB_CRM_EMPLOYEE.IMG
     *
     * @mbg.generated
     */
    public void setImg(String img) {
        this.img = img == null ? null : img.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_EMPLOYEE.SEX
     *
     * @return the value of TB_CRM_EMPLOYEE.SEX
     *
     * @mbg.generated
     */
    public Short getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_EMPLOYEE.SEX
     *
     * @param sex the value for TB_CRM_EMPLOYEE.SEX
     *
     * @mbg.generated
     */
    public void setSex(Short sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_EMPLOYEE.EMAIL
     *
     * @return the value of TB_CRM_EMPLOYEE.EMAIL
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_EMPLOYEE.EMAIL
     *
     * @param email the value for TB_CRM_EMPLOYEE.EMAIL
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_EMPLOYEE.TELEPHONE
     *
     * @return the value of TB_CRM_EMPLOYEE.TELEPHONE
     *
     * @mbg.generated
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_EMPLOYEE.TELEPHONE
     *
     * @param telephone the value for TB_CRM_EMPLOYEE.TELEPHONE
     *
     * @mbg.generated
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_EMPLOYEE.ADDRESS
     *
     * @return the value of TB_CRM_EMPLOYEE.ADDRESS
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_EMPLOYEE.ADDRESS
     *
     * @param address the value for TB_CRM_EMPLOYEE.ADDRESS
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_EMPLOYEE.CREATE_TIME
     *
     * @return the value of TB_CRM_EMPLOYEE.CREATE_TIME
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_EMPLOYEE.CREATE_TIME
     *
     * @param createTime the value for TB_CRM_EMPLOYEE.CREATE_TIME
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_EMPLOYEE.CREATE_USER_ID
     *
     * @return the value of TB_CRM_EMPLOYEE.CREATE_USER_ID
     *
     * @mbg.generated
     */
    public Long getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_EMPLOYEE.CREATE_USER_ID
     *
     * @param createUserId the value for TB_CRM_EMPLOYEE.CREATE_USER_ID
     *
     * @mbg.generated
     */
    public void setCreateUserId(Long createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_EMPLOYEE.UPDATE_TIME
     *
     * @return the value of TB_CRM_EMPLOYEE.UPDATE_TIME
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_EMPLOYEE.UPDATE_TIME
     *
     * @param updateTime the value for TB_CRM_EMPLOYEE.UPDATE_TIME
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_EMPLOYEE.UPDATE_USER_ID
     *
     * @return the value of TB_CRM_EMPLOYEE.UPDATE_USER_ID
     *
     * @mbg.generated
     */
    public Long getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_EMPLOYEE.UPDATE_USER_ID
     *
     * @param updateUserId the value for TB_CRM_EMPLOYEE.UPDATE_USER_ID
     *
     * @mbg.generated
     */
    public void setUpdateUserId(Long updateUserId) {
        this.updateUserId = updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_EMPLOYEE.USER_ID
     *
     * @return the value of TB_CRM_EMPLOYEE.USER_ID
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_EMPLOYEE.USER_ID
     *
     * @param userId the value for TB_CRM_EMPLOYEE.USER_ID
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }
}