package wc.entity;

import java.math.BigDecimal;

public class TbCrmBusiness {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_BUSINESS.ID
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_BUSINESS.NAME
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_BUSINESS.ORIGIN
     *
     * @mbg.generated
     */
    private String origin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_BUSINESS.TYPE
     *
     * @mbg.generated
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_BUSINESS.ESTIMATE_PRICE
     *
     * @mbg.generated
     */
    private Long estimatePrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_BUSINESS.CUSTOMER_ID
     *
     * @mbg.generated
     */
    private Long customerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_BUSINESS.CREATOT_USER_ID
     *
     * @mbg.generated
     */
    private Integer creatotUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_BUSINESS.OWNER_USER_ID
     *
     * @mbg.generated
     */
    private Long ownerUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_BUSINESS.GAIN_RATE
     *
     * @mbg.generated
     */
    private Short gainRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_BUSINESS.TOTAL_AMOUNT
     *
     * @mbg.generated
     */
    private Long totalAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_BUSINESS.SUBTOTAL_VAL
     *
     * @mbg.generated
     */
    private BigDecimal subtotalVal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_BUSINESS.DISCOUNT_PRICE
     *
     * @mbg.generated
     */
    private BigDecimal discountPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_BUSINESS.SALES_PRICE
     *
     * @mbg.generated
     */
    private BigDecimal salesPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_BUSINESS.CREATE_TIME
     *
     * @mbg.generated
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_BUSINESS.UPDATE_TIME
     *
     * @mbg.generated
     */
    private String updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_BUSINESS.UPDATE_USER_ID
     *
     * @mbg.generated
     */
    private Long updateUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_BUSINESS.STATUS_ID
     *
     * @mbg.generated
     */
    private Long statusId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_BUSINESS.TOTAL_PRICE
     *
     * @mbg.generated
     */
    private BigDecimal totalPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_BUSINESS.NEXTSTEP
     *
     * @mbg.generated
     */
    private String nextstep;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_BUSINESS.NEXTSTEP_TIME
     *
     * @mbg.generated
     */
    private String nextstepTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_BUSINESS.DELETE_STATUS
     *
     * @mbg.generated
     */
    private Short deleteStatus = 0;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_BUSINESS.DELETE_USER_ID
     *
     * @mbg.generated
     */
    private Long deleteUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_BUSINESS.DELETE_TIME
     *
     * @mbg.generated
     */
    private String deleteTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_BUSINESS.CONTACTS_ID
     *
     * @mbg.generated
     */
    private Long contactsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_BUSINESS.CONTRACT_ADDRESS
     *
     * @mbg.generated
     */
    private String contractAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_BUSINESS.DESCRPTION
     *
     * @mbg.generated
     */
    private String descrption;
    
    private String dueTime;

    public String getDueTime() {
		return dueTime;
	}

	public void setDueTime(String dueTime) {
		this.dueTime = dueTime;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_BUSINESS.ID
     *
     * @return the value of TB_CRM_BUSINESS.ID
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_BUSINESS.ID
     *
     * @param id the value for TB_CRM_BUSINESS.ID
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_BUSINESS.NAME
     *
     * @return the value of TB_CRM_BUSINESS.NAME
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_BUSINESS.NAME
     *
     * @param name the value for TB_CRM_BUSINESS.NAME
     *
     * @mbg.generated
     */
    
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_BUSINESS.ORIGIN
     *
     * @return the value of TB_CRM_BUSINESS.ORIGIN
     *
     * @mbg.generated
     */
    public String getOrigin() {
        return origin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_BUSINESS.ORIGIN
     *
     * @param origin the value for TB_CRM_BUSINESS.ORIGIN
     *
     * @mbg.generated
     */
    public void setOrigin(String origin) {
        this.origin = origin == null ? null : origin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_BUSINESS.TYPE
     *
     * @return the value of TB_CRM_BUSINESS.TYPE
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_BUSINESS.TYPE
     *
     * @param type the value for TB_CRM_BUSINESS.TYPE
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_BUSINESS.ESTIMATE_PRICE
     *
     * @return the value of TB_CRM_BUSINESS.ESTIMATE_PRICE
     *
     * @mbg.generated
     */
    public Long getEstimatePrice() {
        return estimatePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_BUSINESS.ESTIMATE_PRICE
     *
     * @param estimatePrice the value for TB_CRM_BUSINESS.ESTIMATE_PRICE
     *
     * @mbg.generated
     */
    public void setEstimatePrice(Long estimatePrice) {
        this.estimatePrice = estimatePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_BUSINESS.CUSTOMER_ID
     *
     * @return the value of TB_CRM_BUSINESS.CUSTOMER_ID
     *
     * @mbg.generated
     */
    public Long getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_BUSINESS.CUSTOMER_ID
     *
     * @param customerId the value for TB_CRM_BUSINESS.CUSTOMER_ID
     *
     * @mbg.generated
     */
    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_BUSINESS.CREATOT_USER_ID
     *
     * @return the value of TB_CRM_BUSINESS.CREATOT_USER_ID
     *
     * @mbg.generated
     */
    public Integer getCreatotUserId() {
        return creatotUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_BUSINESS.CREATOT_USER_ID
     *
     * @param id2 the value for TB_CRM_BUSINESS.CREATOT_USER_ID
     *
     * @mbg.generated
     */
    public void setCreatotUserId(Integer id2) {
        this.creatotUserId = id2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_BUSINESS.OWNER_USER_ID
     *
     * @return the value of TB_CRM_BUSINESS.OWNER_USER_ID
     *
     * @mbg.generated
     */
    public Long getOwnerUserId() {
        return ownerUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_BUSINESS.OWNER_USER_ID
     *
     * @param ownerUserId the value for TB_CRM_BUSINESS.OWNER_USER_ID
     *
     * @mbg.generated
     */
    public void setOwnerUserId(Long ownerUserId) {
        this.ownerUserId = ownerUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_BUSINESS.GAIN_RATE
     *
     * @return the value of TB_CRM_BUSINESS.GAIN_RATE
     *
     * @mbg.generated
     */
    public Short getGainRate() {
        return gainRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_BUSINESS.GAIN_RATE
     *
     * @param gainRate the value for TB_CRM_BUSINESS.GAIN_RATE
     *
     * @mbg.generated
     */
    public void setGainRate(Short gainRate) {
        this.gainRate = gainRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_BUSINESS.TOTAL_AMOUNT
     *
     * @return the value of TB_CRM_BUSINESS.TOTAL_AMOUNT
     *
     * @mbg.generated
     */
    public Long getTotalAmount() {
        return totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_BUSINESS.TOTAL_AMOUNT
     *
     * @param totalAmount the value for TB_CRM_BUSINESS.TOTAL_AMOUNT
     *
     * @mbg.generated
     */
    public void setTotalAmount(Long totalAmount) {
        this.totalAmount = totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_BUSINESS.SUBTOTAL_VAL
     *
     * @return the value of TB_CRM_BUSINESS.SUBTOTAL_VAL
     *
     * @mbg.generated
     */
    public BigDecimal getSubtotalVal() {
        return subtotalVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_BUSINESS.SUBTOTAL_VAL
     *
     * @param subtotalVal the value for TB_CRM_BUSINESS.SUBTOTAL_VAL
     *
     * @mbg.generated
     */
    public void setSubtotalVal(BigDecimal subtotalVal) {
        this.subtotalVal = subtotalVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_BUSINESS.DISCOUNT_PRICE
     *
     * @return the value of TB_CRM_BUSINESS.DISCOUNT_PRICE
     *
     * @mbg.generated
     */
    public BigDecimal getDiscountPrice() {
        return discountPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_BUSINESS.DISCOUNT_PRICE
     *
     * @param discountPrice the value for TB_CRM_BUSINESS.DISCOUNT_PRICE
     *
     * @mbg.generated
     */
    public void setDiscountPrice(BigDecimal discountPrice) {
        this.discountPrice = discountPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_BUSINESS.SALES_PRICE
     *
     * @return the value of TB_CRM_BUSINESS.SALES_PRICE
     *
     * @mbg.generated
     */
    public BigDecimal getSalesPrice() {
        return salesPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_BUSINESS.SALES_PRICE
     *
     * @param salesPrice the value for TB_CRM_BUSINESS.SALES_PRICE
     *
     * @mbg.generated
     */
    public void setSalesPrice(BigDecimal salesPrice) {
        this.salesPrice = salesPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_BUSINESS.CREATE_TIME
     *
     * @return the value of TB_CRM_BUSINESS.CREATE_TIME
     *
     * @mbg.generated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_BUSINESS.CREATE_TIME
     *
     * @param createTime the value for TB_CRM_BUSINESS.CREATE_TIME
     *
     * @mbg.generated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_BUSINESS.UPDATE_TIME
     *
     * @return the value of TB_CRM_BUSINESS.UPDATE_TIME
     *
     * @mbg.generated
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_BUSINESS.UPDATE_TIME
     *
     * @param updateTime the value for TB_CRM_BUSINESS.UPDATE_TIME
     *
     * @mbg.generated
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_BUSINESS.UPDATE_USER_ID
     *
     * @return the value of TB_CRM_BUSINESS.UPDATE_USER_ID
     *
     * @mbg.generated
     */
    public Long getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_BUSINESS.UPDATE_USER_ID
     *
     * @param updateUserId the value for TB_CRM_BUSINESS.UPDATE_USER_ID
     *
     * @mbg.generated
     */
    public void setUpdateUserId(Long updateUserId) {
        this.updateUserId = updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_BUSINESS.STATUS_ID
     *
     * @return the value of TB_CRM_BUSINESS.STATUS_ID
     *
     * @mbg.generated
     */
    public Long getStatusId() {
        return statusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_BUSINESS.STATUS_ID
     *
     * @param statusId the value for TB_CRM_BUSINESS.STATUS_ID
     *
     * @mbg.generated
     */
    public void setStatusId(Long statusId) {
        this.statusId = statusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_BUSINESS.TOTAL_PRICE
     *
     * @return the value of TB_CRM_BUSINESS.TOTAL_PRICE
     *
     * @mbg.generated
     */
    public BigDecimal getTotalPrice() {
        return totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_BUSINESS.TOTAL_PRICE
     *
     * @param totalPrice the value for TB_CRM_BUSINESS.TOTAL_PRICE
     *
     * @mbg.generated
     */
    public void setTotalPrice(BigDecimal totalPrice) {
        this.totalPrice = totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_BUSINESS.NEXTSTEP
     *
     * @return the value of TB_CRM_BUSINESS.NEXTSTEP
     *
     * @mbg.generated
     */
    public String getNextstep() {
        return nextstep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_BUSINESS.NEXTSTEP
     *
     * @param nextstep the value for TB_CRM_BUSINESS.NEXTSTEP
     *
     * @mbg.generated
     */
    public void setNextstep(String nextstep) {
        this.nextstep = nextstep == null ? null : nextstep.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_BUSINESS.NEXTSTEP_TIME
     *
     * @return the value of TB_CRM_BUSINESS.NEXTSTEP_TIME
     *
     * @mbg.generated
     */
    public String getNextstepTime() {
        return nextstepTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_BUSINESS.NEXTSTEP_TIME
     *
     * @param string the value for TB_CRM_BUSINESS.NEXTSTEP_TIME
     *
     * @mbg.generated
     */
    public void setNextstepTime(String string) {
        this.nextstepTime = string;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_BUSINESS.DELETE_STATUS
     *
     * @return the value of TB_CRM_BUSINESS.DELETE_STATUS
     *
     * @mbg.generated
     */
    public Short getDeleteStatus() {
        return deleteStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_BUSINESS.DELETE_STATUS
     *
     * @param deleteStatus the value for TB_CRM_BUSINESS.DELETE_STATUS
     *
     * @mbg.generated
     */
    public void setDeleteStatus(Short deleteStatus) {
        this.deleteStatus = deleteStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_BUSINESS.DELETE_USER_ID
     *
     * @return the value of TB_CRM_BUSINESS.DELETE_USER_ID
     *
     * @mbg.generated
     */
    public Long getDeleteUserId() {
        return deleteUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_BUSINESS.DELETE_USER_ID
     *
     * @param deleteUserId the value for TB_CRM_BUSINESS.DELETE_USER_ID
     *
     * @mbg.generated
     */
    public void setDeleteUserId(Long deleteUserId) {
        this.deleteUserId = deleteUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_BUSINESS.DELETE_TIME
     *
     * @return the value of TB_CRM_BUSINESS.DELETE_TIME
     *
     * @mbg.generated
     */
    public String getDeleteTime() {
        return deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_BUSINESS.DELETE_TIME
     *
     * @param deleteTime the value for TB_CRM_BUSINESS.DELETE_TIME
     *
     * @mbg.generated
     */
    public void setDeleteTime(String deleteTime) {
        this.deleteTime = deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_BUSINESS.CONTACTS_ID
     *
     * @return the value of TB_CRM_BUSINESS.CONTACTS_ID
     *
     * @mbg.generated
     */
    public Long getContactsId() {
        return contactsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_BUSINESS.CONTACTS_ID
     *
     * @param contactsId the value for TB_CRM_BUSINESS.CONTACTS_ID
     *
     * @mbg.generated
     */
    public void setContactsId(Long contactsId) {
        this.contactsId = contactsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_BUSINESS.CONTRACT_ADDRESS
     *
     * @return the value of TB_CRM_BUSINESS.CONTRACT_ADDRESS
     *
     * @mbg.generated
     */
    public String getContractAddress() {
        return contractAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_BUSINESS.CONTRACT_ADDRESS
     *
     * @param contractAddress the value for TB_CRM_BUSINESS.CONTRACT_ADDRESS
     *
     * @mbg.generated
     */
    public void setContractAddress(String contractAddress) {
        this.contractAddress = contractAddress == null ? null : contractAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_BUSINESS.DESCRPTION
     *
     * @return the value of TB_CRM_BUSINESS.DESCRPTION
     *
     * @mbg.generated
     */
    public String getDescrption() {
        return descrption;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_BUSINESS.DESCRPTION
     *
     * @param descrption the value for TB_CRM_BUSINESS.DESCRPTION
     *
     * @mbg.generated
     */
    public void setDescrption(String descrption) {
        this.descrption = descrption == null ? null : descrption.trim();
    }

	@Override
	public String toString() {
		return "TbCrmBusiness [id=" + id + ", name=" + name + ", origin=" + origin + ", type=" + type
				+ ", estimatePrice=" + estimatePrice + ", customerId=" + customerId + ", creatotUserId=" + creatotUserId
				+ ", ownerUserId=" + ownerUserId + ", gainRate=" + gainRate + ", totalAmount=" + totalAmount
				+ ", subtotalVal=" + subtotalVal + ", discountPrice=" + discountPrice + ", salesPrice=" + salesPrice
				+ ", createTime=" + createTime + ", updateTime=" + updateTime + ", updateUserId=" + updateUserId
				+ ", statusId=" + statusId + ", totalPrice=" + totalPrice + ", nextstep=" + nextstep + ", nextstepTime="
				+ nextstepTime + ", deleteStatus=" + deleteStatus + ", deleteUserId=" + deleteUserId + ", deleteTime="
				+ deleteTime + ", contactsId=" + contactsId + ", contractAddress=" + contractAddress + ", descrption="
				+ descrption + ", dueTime=" + dueTime + "]";
	}
    
}