package wc.entity;

import java.util.Date;

public class TbCrmLoginHistory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_LOGIN_HISTORY.ID
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_LOGIN_HISTORY.USER_ID
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_LOGIN_HISTORY.LOGIN_ID
     *
     * @mbg.generated
     */
    private Date loginId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_LOGIN_HISTORY.LOGIN_IP
     *
     * @mbg.generated
     */
    private String loginIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_LOGIN_HISTORY.LOGIN_STATUS
     *
     * @mbg.generated
     */
    private Short loginStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_LOGIN_HISTORY.ID
     *
     * @return the value of TB_CRM_LOGIN_HISTORY.ID
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_LOGIN_HISTORY.ID
     *
     * @param id the value for TB_CRM_LOGIN_HISTORY.ID
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_LOGIN_HISTORY.USER_ID
     *
     * @return the value of TB_CRM_LOGIN_HISTORY.USER_ID
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_LOGIN_HISTORY.USER_ID
     *
     * @param userId the value for TB_CRM_LOGIN_HISTORY.USER_ID
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_LOGIN_HISTORY.LOGIN_ID
     *
     * @return the value of TB_CRM_LOGIN_HISTORY.LOGIN_ID
     *
     * @mbg.generated
     */
    public Date getLoginId() {
        return loginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_LOGIN_HISTORY.LOGIN_ID
     *
     * @param loginId the value for TB_CRM_LOGIN_HISTORY.LOGIN_ID
     *
     * @mbg.generated
     */
    public void setLoginId(Date loginId) {
        this.loginId = loginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_LOGIN_HISTORY.LOGIN_IP
     *
     * @return the value of TB_CRM_LOGIN_HISTORY.LOGIN_IP
     *
     * @mbg.generated
     */
    public String getLoginIp() {
        return loginIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_LOGIN_HISTORY.LOGIN_IP
     *
     * @param loginIp the value for TB_CRM_LOGIN_HISTORY.LOGIN_IP
     *
     * @mbg.generated
     */
    public void setLoginIp(String loginIp) {
        this.loginIp = loginIp == null ? null : loginIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_LOGIN_HISTORY.LOGIN_STATUS
     *
     * @return the value of TB_CRM_LOGIN_HISTORY.LOGIN_STATUS
     *
     * @mbg.generated
     */
    public Short getLoginStatus() {
        return loginStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_LOGIN_HISTORY.LOGIN_STATUS
     *
     * @param loginStatus the value for TB_CRM_LOGIN_HISTORY.LOGIN_STATUS
     *
     * @mbg.generated
     */
    public void setLoginStatus(Short loginStatus) {
        this.loginStatus = loginStatus;
    }
}