package wc.entity;

import java.util.Date;

public class TbCrmSmsRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_SMS_RECORD.ID
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_SMS_RECORD.USER_ID
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_SMS_RECORD.TELEPHONE
     *
     * @mbg.generated
     */
    private String telephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_SMS_RECORD.SENDTIME
     *
     * @mbg.generated
     */
    private String sendtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_SMS_RECORD.CONTENT
     *
     * @mbg.generated
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_SMS_RECORD.ID
     *
     * @return the value of TB_CRM_SMS_RECORD.ID
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_SMS_RECORD.ID
     *
     * @param id the value for TB_CRM_SMS_RECORD.ID
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_SMS_RECORD.USER_ID
     *
     * @return the value of TB_CRM_SMS_RECORD.USER_ID
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_SMS_RECORD.USER_ID
     *
     * @param userId the value for TB_CRM_SMS_RECORD.USER_ID
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_SMS_RECORD.TELEPHONE
     *
     * @return the value of TB_CRM_SMS_RECORD.TELEPHONE
     *
     * @mbg.generated
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_SMS_RECORD.TELEPHONE
     *
     * @param telephone the value for TB_CRM_SMS_RECORD.TELEPHONE
     *
     * @mbg.generated
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_SMS_RECORD.SENDTIME
     *
     * @return the value of TB_CRM_SMS_RECORD.SENDTIME
     *
     * @mbg.generated
     */
    public String getSendtime() {
        return sendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_SMS_RECORD.SENDTIME
     *
     * @param sendtime the value for TB_CRM_SMS_RECORD.SENDTIME
     *
     * @mbg.generated
     */
    public void setSendtime(String sendtime) {
        this.sendtime = sendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_SMS_RECORD.CONTENT
     *
     * @return the value of TB_CRM_SMS_RECORD.CONTENT
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_SMS_RECORD.CONTENT
     *
     * @param content the value for TB_CRM_SMS_RECORD.CONTENT
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

	@Override
	public String toString() {
		return "TbCrmSmsRecord [id=" + id + ", userId=" + userId + ", telephone=" + telephone + ", sendtime=" + sendtime
				+ ", content=" + content + "]";
	}
    
}