package wc.entity;

public class TbCrmEmailTemplate {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_EMAIL_TEMPLATE.ID
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_EMAIL_TEMPLATE.SUBJECT
     *
     * @mbg.generated
     */
    private String subject;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_EMAIL_TEMPLATE.TITLE
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_EMAIL_TEMPLATE.CONTENT
     *
     * @mbg.generated
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_EMAIL_TEMPLATE.ORDER_ID
     *
     * @mbg.generated
     */
    private Long orderId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_EMAIL_TEMPLATE.ID
     *
     * @return the value of TB_CRM_EMAIL_TEMPLATE.ID
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_EMAIL_TEMPLATE.ID
     *
     * @param id the value for TB_CRM_EMAIL_TEMPLATE.ID
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_EMAIL_TEMPLATE.SUBJECT
     *
     * @return the value of TB_CRM_EMAIL_TEMPLATE.SUBJECT
     *
     * @mbg.generated
     */
    public String getSubject() {
        return subject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_EMAIL_TEMPLATE.SUBJECT
     *
     * @param subject the value for TB_CRM_EMAIL_TEMPLATE.SUBJECT
     *
     * @mbg.generated
     */
    public void setSubject(String subject) {
        this.subject = subject == null ? null : subject.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_EMAIL_TEMPLATE.TITLE
     *
     * @return the value of TB_CRM_EMAIL_TEMPLATE.TITLE
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_EMAIL_TEMPLATE.TITLE
     *
     * @param title the value for TB_CRM_EMAIL_TEMPLATE.TITLE
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_EMAIL_TEMPLATE.CONTENT
     *
     * @return the value of TB_CRM_EMAIL_TEMPLATE.CONTENT
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_EMAIL_TEMPLATE.CONTENT
     *
     * @param content the value for TB_CRM_EMAIL_TEMPLATE.CONTENT
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_EMAIL_TEMPLATE.ORDER_ID
     *
     * @return the value of TB_CRM_EMAIL_TEMPLATE.ORDER_ID
     *
     * @mbg.generated
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_EMAIL_TEMPLATE.ORDER_ID
     *
     * @param orderId the value for TB_CRM_EMAIL_TEMPLATE.ORDER_ID
     *
     * @mbg.generated
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

	@Override
	public String toString() {
		return "TbCrmEmailTemplate [id=" + id + ", subject=" + subject + ", title=" + title + ", content=" + content
				+ ", orderId=" + orderId + "]";
	}
    
}