package wc.entity;

import java.math.BigDecimal;
import java.util.Date;

public class TbCrmProduct {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_PRODUCT.ID
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_PRODUCT.CATEGORY_ID
     *
     * @mbg.generated
     */
    private int categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_PRODUCT.NAME
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_PRODUCT.CREATOR_USER_ID
     *
     * @mbg.generated
     */
    private int creatorUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_PRODUCT.COST_PRICE
     *
     * @mbg.generated
     */
    private BigDecimal costPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_PRODUCT.SUGGESTED_PRICE
     *
     * @mbg.generated
     */
    private BigDecimal suggestedPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_PRODUCT.DEVELOPMENT_TEAM
     *
     * @mbg.generated
     */
    private String developmentTeam;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_PRODUCT.DEVELOPMENT_TIME
     *
     * @mbg.generated
     */
    private String developmentTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_PRODUCT.LINK
     *
     * @mbg.generated
     */
    private String link;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_PRODUCT.CREATE_TIME
     *
     * @mbg.generated
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_PRODUCT.UPDATE_TIME
     *
     * @mbg.generated
     */
    private String updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_PRODUCT.DESCRIPTION
     *
     * @mbg.generated
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_PRODUCT.ID
     *
     * @return the value of TB_CRM_PRODUCT.ID
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_PRODUCT.ID
     *
     * @param id the value for TB_CRM_PRODUCT.ID
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_PRODUCT.CATEGORY_ID
     *
     * @return the value of TB_CRM_PRODUCT.CATEGORY_ID
     *
     * @mbg.generated
     */
    public int getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_PRODUCT.CATEGORY_ID
     *
     * @param categoryId the value for TB_CRM_PRODUCT.CATEGORY_ID
     *
     * @mbg.generated
     */
    public void setCategoryId(int categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_PRODUCT.NAME
     *
     * @return the value of TB_CRM_PRODUCT.NAME
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_PRODUCT.NAME
     *
     * @param name the value for TB_CRM_PRODUCT.NAME
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_PRODUCT.CREATOR_USER_ID
     *
     * @return the value of TB_CRM_PRODUCT.CREATOR_USER_ID
     *
     * @mbg.generated
     */
    public int getCreatorUserId() {
        return creatorUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_PRODUCT.CREATOR_USER_ID
     *
     * @param creatorUserId the value for TB_CRM_PRODUCT.CREATOR_USER_ID
     *
     * @mbg.generated
     */
    public void setCreatorUserId(int creatorUserId) {
        this.creatorUserId = creatorUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_PRODUCT.COST_PRICE
     *
     * @return the value of TB_CRM_PRODUCT.COST_PRICE
     *
     * @mbg.generated
     */
    public BigDecimal getCostPrice() {
        return costPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_PRODUCT.COST_PRICE
     *
     * @param costPrice the value for TB_CRM_PRODUCT.COST_PRICE
     *
     * @mbg.generated
     */
    public void setCostPrice(BigDecimal costPrice) {
        this.costPrice = costPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_PRODUCT.SUGGESTED_PRICE
     *
     * @return the value of TB_CRM_PRODUCT.SUGGESTED_PRICE
     *
     * @mbg.generated
     */
    public BigDecimal getSuggestedPrice() {
        return suggestedPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_PRODUCT.SUGGESTED_PRICE
     *
     * @param suggestedPrice the value for TB_CRM_PRODUCT.SUGGESTED_PRICE
     *
     * @mbg.generated
     */
    public void setSuggestedPrice(BigDecimal suggestedPrice) {
        this.suggestedPrice = suggestedPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_PRODUCT.DEVELOPMENT_TEAM
     *
     * @return the value of TB_CRM_PRODUCT.DEVELOPMENT_TEAM
     *
     * @mbg.generated
     */
    public String getDevelopmentTeam() {
        return developmentTeam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_PRODUCT.DEVELOPMENT_TEAM
     *
     * @param developmentTeam the value for TB_CRM_PRODUCT.DEVELOPMENT_TEAM
     *
     * @mbg.generated
     */
    public void setDevelopmentTeam(String developmentTeam) {
        this.developmentTeam = developmentTeam == null ? null : developmentTeam.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_PRODUCT.DEVELOPMENT_TIME
     *
     * @return the value of TB_CRM_PRODUCT.DEVELOPMENT_TIME
     *
     * @mbg.generated
     */
    public String getDevelopmentTime() {
        return developmentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_PRODUCT.DEVELOPMENT_TIME
     *
     * @param developmentTime the value for TB_CRM_PRODUCT.DEVELOPMENT_TIME
     *
     * @mbg.generated
     */
    public void setDevelopmentTime(String developmentTime) {
        this.developmentTime = developmentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_PRODUCT.LINK
     *
     * @return the value of TB_CRM_PRODUCT.LINK
     *
     * @mbg.generated
     */
    public String getLink() {
        return link;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_PRODUCT.LINK
     *
     * @param link the value for TB_CRM_PRODUCT.LINK
     *
     * @mbg.generated
     */
    public void setLink(String link) {
        this.link = link == null ? null : link.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_PRODUCT.CREATE_TIME
     *
     * @return the value of TB_CRM_PRODUCT.CREATE_TIME
     *
     * @mbg.generated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_PRODUCT.CREATE_TIME
     *
     * @param createTime the value for TB_CRM_PRODUCT.CREATE_TIME
     *
     * @mbg.generated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_PRODUCT.UPDATE_TIME
     *
     * @return the value of TB_CRM_PRODUCT.UPDATE_TIME
     *
     * @mbg.generated
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_PRODUCT.UPDATE_TIME
     *
     * @param updateTime the value for TB_CRM_PRODUCT.UPDATE_TIME
     *
     * @mbg.generated
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_PRODUCT.DESCRIPTION
     *
     * @return the value of TB_CRM_PRODUCT.DESCRIPTION
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_PRODUCT.DESCRIPTION
     *
     * @param description the value for TB_CRM_PRODUCT.DESCRIPTION
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

	@Override
	public String toString() {
		return "TbCrmProduct [id=" + id + ", categoryId=" + categoryId + ", name=" + name + ", creatorUserId="
				+ creatorUserId + ", costPrice=" + costPrice + ", suggestedPrice=" + suggestedPrice
				+ ", developmentTeam=" + developmentTeam + ", developmentTime=" + developmentTime + ", link=" + link
				+ ", createTime=" + createTime + ", updateTime=" + updateTime + ", description=" + description + "]";
	}
    
}