package wc.entity;

public class TbSystemUserRole {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SYSTEM_USER_ROLE.USER_ID
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SYSTEM_USER_ROLE.ROLE_ID
     *
     * @mbg.generated
     */
    private Integer roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SYSTEM_USER_ROLE.USER_ID
     *
     * @return the value of TB_SYSTEM_USER_ROLE.USER_ID
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SYSTEM_USER_ROLE.USER_ID
     *
     * @param userId the value for TB_SYSTEM_USER_ROLE.USER_ID
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SYSTEM_USER_ROLE.ROLE_ID
     *
     * @return the value of TB_SYSTEM_USER_ROLE.ROLE_ID
     *
     * @mbg.generated
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SYSTEM_USER_ROLE.ROLE_ID
     *
     * @param roleId the value for TB_SYSTEM_USER_ROLE.ROLE_ID
     *
     * @mbg.generated
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }
}