package wc.entity;

import java.util.Date;

public class TbSystemUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SYSTEM_USER.USER_ID
     *
     * @mbg.generated
     */
    private int userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SYSTEM_USER.USERNAME
     *
     * @mbg.generated
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SYSTEM_USER.PASSWORD
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SYSTEM_USER.CREATE_TIME
     *
     * @mbg.generated
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SYSTEM_USER.UPDATE_TIME
     *
     * @mbg.generated
     */
    private String updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SYSTEM_USER.USER_ID
     *
     * @return the value of TB_SYSTEM_USER.USER_ID
     *
     * @mbg.generated
     */
    public int getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SYSTEM_USER.USER_ID
     *
     * @param userId the value for TB_SYSTEM_USER.USER_ID
     *
     * @mbg.generated
     */
    public void setUserId(int userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SYSTEM_USER.USERNAME
     *
     * @return the value of TB_SYSTEM_USER.USERNAME
     *
     * @mbg.generated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SYSTEM_USER.USERNAME
     *
     * @param username the value for TB_SYSTEM_USER.USERNAME
     *
     * @mbg.generated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SYSTEM_USER.PASSWORD
     *
     * @return the value of TB_SYSTEM_USER.PASSWORD
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SYSTEM_USER.PASSWORD
     *
     * @param password the value for TB_SYSTEM_USER.PASSWORD
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SYSTEM_USER.CREATE_TIME
     *
     * @return the value of TB_SYSTEM_USER.CREATE_TIME
     *
     * @mbg.generated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SYSTEM_USER.CREATE_TIME
     *
     * @param createTime the value for TB_SYSTEM_USER.CREATE_TIME
     *
     * @mbg.generated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SYSTEM_USER.UPDATE_TIME
     *
     * @return the value of TB_SYSTEM_USER.UPDATE_TIME
     *
     * @mbg.generated
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SYSTEM_USER.UPDATE_TIME
     *
     * @param updateTime the value for TB_SYSTEM_USER.UPDATE_TIME
     *
     * @mbg.generated
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime;
    }

	@Override
	public String toString() {
		return "TbSystemUser [userId=" + userId + ", username=" + username + ", password=" + password + ", createTime="
				+ createTime + ", updateTime=" + updateTime + "]";
	}
    
}