package wc.entity;

public class TbSystemRoleFunction {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SYSTEM_ROLE_FUNCTION.FUNC_ID
     *
     * @mbg.generated
     */
    private Integer funcId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SYSTEM_ROLE_FUNCTION.ROLE_ID
     *
     * @mbg.generated
     */
    private Integer roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SYSTEM_ROLE_FUNCTION.FUNC_ID
     *
     * @return the value of TB_SYSTEM_ROLE_FUNCTION.FUNC_ID
     *
     * @mbg.generated
     */
    public Integer getFuncId() {
        return funcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SYSTEM_ROLE_FUNCTION.FUNC_ID
     *
     * @param funcId the value for TB_SYSTEM_ROLE_FUNCTION.FUNC_ID
     *
     * @mbg.generated
     */
    public void setFuncId(Integer funcId) {
        this.funcId = funcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SYSTEM_ROLE_FUNCTION.ROLE_ID
     *
     * @return the value of TB_SYSTEM_ROLE_FUNCTION.ROLE_ID
     *
     * @mbg.generated
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SYSTEM_ROLE_FUNCTION.ROLE_ID
     *
     * @param roleId the value for TB_SYSTEM_ROLE_FUNCTION.ROLE_ID
     *
     * @mbg.generated
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }
}