package wc.entity;

import java.util.Date;

public class TbSystemRole {
	
	private boolean flag;
    public boolean isFlag() {
		return flag;
	}

	public void setFlag(boolean flag) {
		this.flag = flag;
	}
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SYSTEM_ROLE.ROLE_ID
     *
     * @mbg.generated
     */
    private Integer roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SYSTEM_ROLE.ROLE_NAME
     *
     * @mbg.generated
     */
    private String roleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SYSTEM_ROLE.NOTE
     *
     * @mbg.generated
     */
    private String note;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SYSTEM_ROLE.STATUS
     *
     * @mbg.generated
     */
    private Short status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SYSTEM_ROLE.CREATE_TIME
     *
     * @mbg.generated
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SYSTEM_ROLE.UPDATE_TIME
     *
     * @mbg.generated
     */
    private String updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SYSTEM_ROLE.ROLE_ID
     *
     * @return the value of TB_SYSTEM_ROLE.ROLE_ID
     *
     * @mbg.generated
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SYSTEM_ROLE.ROLE_ID
     *
     * @param roleId the value for TB_SYSTEM_ROLE.ROLE_ID
     *
     * @mbg.generated
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SYSTEM_ROLE.ROLE_NAME
     *
     * @return the value of TB_SYSTEM_ROLE.ROLE_NAME
     *
     * @mbg.generated
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SYSTEM_ROLE.ROLE_NAME
     *
     * @param roleName the value for TB_SYSTEM_ROLE.ROLE_NAME
     *
     * @mbg.generated
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SYSTEM_ROLE.NOTE
     *
     * @return the value of TB_SYSTEM_ROLE.NOTE
     *
     * @mbg.generated
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SYSTEM_ROLE.NOTE
     *
     * @param note the value for TB_SYSTEM_ROLE.NOTE
     *
     * @mbg.generated
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SYSTEM_ROLE.STATUS
     *
     * @return the value of TB_SYSTEM_ROLE.STATUS
     *
     * @mbg.generated
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SYSTEM_ROLE.STATUS
     *
     * @param status the value for TB_SYSTEM_ROLE.STATUS
     *
     * @mbg.generated
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SYSTEM_ROLE.CREATE_TIME
     *
     * @return the value of TB_SYSTEM_ROLE.CREATE_TIME
     *
     * @mbg.generated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SYSTEM_ROLE.CREATE_TIME
     *
     * @param createTime the value for TB_SYSTEM_ROLE.CREATE_TIME
     *
     * @mbg.generated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SYSTEM_ROLE.UPDATE_TIME
     *
     * @return the value of TB_SYSTEM_ROLE.UPDATE_TIME
     *
     * @mbg.generated
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SYSTEM_ROLE.UPDATE_TIME
     *
     * @param updateTime the value for TB_SYSTEM_ROLE.UPDATE_TIME
     *
     * @mbg.generated
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime;
    }

	@Override
	public String toString() {
		return "TbSystemRole [roleId=" + roleId + ", roleName=" + roleName + ", note=" + note + ", status=" + status
				+ ", createTime=" + createTime + ", updateTime=" + updateTime + "]";
	}
    
}