package wc.entity;

public class TbSystemFunction {
	private boolean flag;
    public boolean isFlag() {
		return flag;
	}

	public void setFlag(boolean flag) {
		this.flag = flag;
	}
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SYSTEM_FUNCTION.FUNC_ID
     *
     * @mbg.generated
     */
    private Integer funcId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SYSTEM_FUNCTION.FUNC_NAME
     *
     * @mbg.generated
     */
    private String funcName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SYSTEM_FUNCTION.FUNC_URL
     *
     * @mbg.generated
     */
    private String funcUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SYSTEM_FUNCTION.PARENT_ID
     *
     * @mbg.generated
     */
    private String parentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SYSTEM_FUNCTION.FUNC_ID
     *
     * @return the value of TB_SYSTEM_FUNCTION.FUNC_ID
     *
     * @mbg.generated
     */
    public Integer getFuncId() {
        return funcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SYSTEM_FUNCTION.FUNC_ID
     *
     * @param funcId the value for TB_SYSTEM_FUNCTION.FUNC_ID
     *
     * @mbg.generated
     */
    public void setFuncId(Integer funcId) {
        this.funcId = funcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SYSTEM_FUNCTION.FUNC_NAME
     *
     * @return the value of TB_SYSTEM_FUNCTION.FUNC_NAME
     *
     * @mbg.generated
     */
    public String getFuncName() {
        return funcName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SYSTEM_FUNCTION.FUNC_NAME
     *
     * @param funcName the value for TB_SYSTEM_FUNCTION.FUNC_NAME
     *
     * @mbg.generated
     */
    public void setFuncName(String funcName) {
        this.funcName = funcName == null ? null : funcName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SYSTEM_FUNCTION.FUNC_URL
     *
     * @return the value of TB_SYSTEM_FUNCTION.FUNC_URL
     *
     * @mbg.generated
     */
    public String getFuncUrl() {
        return funcUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SYSTEM_FUNCTION.FUNC_URL
     *
     * @param funcUrl the value for TB_SYSTEM_FUNCTION.FUNC_URL
     *
     * @mbg.generated
     */
    public void setFuncUrl(String funcUrl) {
        this.funcUrl = funcUrl == null ? null : funcUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SYSTEM_FUNCTION.PARENT_ID
     *
     * @return the value of TB_SYSTEM_FUNCTION.PARENT_ID
     *
     * @mbg.generated
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SYSTEM_FUNCTION.PARENT_ID
     *
     * @param parentId the value for TB_SYSTEM_FUNCTION.PARENT_ID
     *
     * @mbg.generated
     */
    public void setParentId(String parentId) {
        this.parentId = parentId == null ? null : parentId.trim();
    }
}